### ISSUE TITLE
how connect to mongodb?

### ISSUE THREAD

**Issue by krzychu2** [matteofabbri/AspNetCore.Identity.Mongo#1]
Hello,

how change connection string to mongodb?

**Comment by matteofabbri** [comment]
The connection to mongo is handled by another package Mongolino.
Just set the connection string as shown here:

https://github.com/matteofabbri/AspNetCore.Identity.Mongo/blob/master/Examples/SampleWebSite/appsettings.json

Or here:

https://github.com/matteofabbri/Mongolino/issues/4

**Comment by matteofabbri** [comment]
@krzychu2 Updated the library to use the same approach of the "standard one"

            services.AddMongoIdentityProvider<ApplicationUser, ApplicationRole>("mongodb://localhost/maddalena", options =>
             {
                 options.Password.RequiredLength = 6;
                 options.Password.RequireLowercase = false;
                 options.Password.RequireUppercase = false;
                 options.Password.RequireNonAlphanumeric = false;
                 options.Password.RequireDigit = false;
             });
