### ISSUE TITLE
MongoIdentityOptions missing Passord configuration

### ISSUE THREAD

**Issue by Maciejszuchta** [matteofabbri/AspNetCore.Identity.Mongo#10]
After updating to newest version I cannot use Password options in MongoDbProvider configuratioin

` services.AddIdentityMongoDbProvider<ApplicationUser>(options =>`
          ` {`
                `         options.ConnectionString = connectionString;`
                 `   options.Password.RequiredLength = 6;`
             `       options.Password.RequireLowercase = true;`
               `     options.Password.RequireUppercase = true;`
             `       options.Password.RequireNonAlphanumeric = true;`
                `    options.Password.RequireDigit = true;`
         `   });`

**Comment by 7Kronos** [comment]
You have to specity Role type to switch to next override :

```csharp
services.AddIdentityMongoDbProvider<ApplicationUser, MongoRole>(identityOptions =>
{
      options.ConnectionString = connectionString;
      options.Password.RequiredLength = 6;
      options.Password.RequireLowercase = true;
      options.Password.RequireUppercase = true;
      options.Password.RequireNonAlphanumeric = true;
      options.Password.RequireDigit = true;
}
```

> Notice the second type parameter "MongoRole".

**Comment by Maciejszuchta** [comment]
But Identity options are missing Password property in the newest version.
`public class MongoIdentityOptions{`
 
    
    public string ConnectionString { get; set; } = "mongodb://localhost/default";`

    public string UsersCollection { get; set; } = "Users";

    public string RolesCollection { get; set; } = "Roles";
  `}`

**Comment by 7Kronos** [comment]
I'm not sure what you mean. This works fine with last aspnet core version (2.1.1).

You have to use this signature if you want to have access to both MongoIdentityOptions and IdentityOptions.

```csharp
IServiceCollection AddIdentityMongoDbProvider<TUser, TRole>(this IServiceCollection services,
			Action<IdentityOptions> setupIdentityAction, Action<MongoIdentityOptions> setupDatabaseAction)
```

Try this :

```csharp
                services.AddIdentityMongoDbProvider<ApplicationUser, MongoRole>(identityOptions =>
                {
                    identityOptions.Password.RequiredLength = 6;
                    identityOptions.Password.RequireLowercase = true;
                    identityOptions.Password.RequireUppercase = true;
                    identityOptions.Password.RequireNonAlphanumeric = true;
                    identityOptions.Password.RequireDigit = true;
                }, options =>
                {
                    options.ConnectionString = connectionString;
                });
```

**Comment by Maciejszuchta** [comment]
![administratormodule - microsoft visual studio](https://user-images.githubusercontent.com/12434636/48483793-b0eb4a00-e814-11e8-9506-63db5be9ab75.jpg)

This is what i get when I use Password option.

**Comment by 7Kronos** [comment]
@Maciejszuchta You have to specify both delegates to access identity options. Copy paste my code should work.

**Comment by Maciejszuchta** [comment]
@7Kronos yes indeed it works :)

**Comment by matteofabbri** [comment]
Thanks a lot :)
