### ISSUE TITLE
[BUG] 404 on /.well-known/openid-configuration

### ISSUE THREAD

**Issue by ChristPetitjean** [matteofabbri/AspNetCore.Identity.Mongo#102]
**Describe the bug**
When trying to use the server to authenticate via openid like identity server, we get a 404 on the discovery url (/.well-known/openid-configuration)

**To Reproduce**
1. Download and run the sample app
2. Create an SPA with the oidc-client package
3. try to connect

**Expected behavior**
The discovery url respond and wen are redirected to the login page

**Environment (please complete the following information):**
 - .Net 5
 - Package Version:8.2.0

**Additional context**
SPA: VueJs 3 + Vite + oidc-client package

**Comment by vova3211** [comment]
Hi @ChristPetitjean ,
Library by itself doesn't provide such endpoints and funtionality.

I assume you are trying to use IdentityServer. If yes, propably something set up incorrect. Please provide information how you configure it and I'll try to help you.

**Comment by vova3211** [comment]
Closed as no response for long time. If you'll have any questions, re-open it.
