### ISSUE TITLE
[BUG] Resetting User Password

### ISSUE THREAD

**Issue by cyrilCodePro** [matteofabbri/AspNetCore.Identity.Mongo#104]
**Describe the bug**
When resetting a user password it does not effect changes

**To Reproduce**
1. From  the `UserManager<T> ` call the `ResetPasswordAsync `method and pass the necessary parameters

**Expected behavior**
It should be able to reflect the new password to change .

**Screenshots**
N/A

**Environment (please complete the following information):**
 - .Net Core version: [e.g. .Net Core 5.0]
 - Package Version: [8.2.0]

**Comment by vova3211** [comment]
Hi @cyrilCodePro ,
I don't see any problems with resetting password. `.ResetPasswordAsync` returns `Microsoft.AspNetCore.Identity.IdentityResult` that has Errors property with description/s why password is not changed.

Please check that first.

Possible issues: invalid reset token, password not follows minimal rules etc.

**Comment by vova3211** [comment]
Closed - no response for long time.
