### ISSUE TITLE
Question - .NET 6

### ISSUE THREAD

**Issue by iXyles** [matteofabbri/AspNetCore.Identity.Mongo#107]
Hello,

I am just curious to see if you have any plans of making a port over to .NET 6 when they officially release the 6.0 version.

Or if your plan is to stay with the more flexible solution of .Netstandard 2.1+

I saw that someone had already commented regarding the security questions around it with: https://github.com/matteofabbri/AspNetCore.Identity.Mongo/pull/106 and I can see this would also add in the possibility of improved support for .NET 6 similar to the .NET 5 target.

**Comment by vova3211** [comment]
Hi @iXyles !
Yes, we are going to support .NET 6 after it's official release.

**Comment by mahyar1386** [comment]
> Hi @iXyles ! Yes, we are going to support .NET 6 after it's official release.

The official release of .Net 6 is now available. Does this project support .Net 6?
