### ISSUE TITLE
'AuthenticatorKey' does not match any field or property of class AspNetCore.Identity.Mongo.Model.MongoUser

### ISSUE THREAD

**Issue by johnkwaters** [matteofabbri/AspNetCore.Identity.Mongo#111]
I got this after upgrading to the latest version. Is there a migration to run or some mitigation?

**Comment by vova3211** [comment]
Hi @johnkwaters , 
There are 2 possible solutions for you right now:
1. remove `AuthenticatorKey` property from every user record in db. (probably RecoveryCodes also)
2. use [BsonIgnoreExtraElements] attribute on top of class that inherited from MongoUser. If you use MongoUser directly, create new class inherited from MongoUser. And use it instead.

it's known issue. We are working on it right now.
