### ISSUE TITLE
Unable to make User collection indexes unique

### ISSUE THREAD

**Issue by martin-masse** [matteofabbri/AspNetCore.Identity.Mongo#118]
Hi,

I was looking at making the index on NormalizedEmail and NormalizedUserName unique. It does not seems to be possible.

I can't override this behavior by registering my own IUserStore<> that inherit from AspNetCore.Identity.Mongo.Stores.UserStore.  It is not possible since EnsureIndex is called in the UserStore constructor and it will always be called.

I have considered adding another index but MongoDb is complaining that another one already exists for the same column.

The possibilities I see here is to either

- Change EnsureIndex to create unique Index (this could be a config option)
- Provide an empty constructor on AspNetCore.Identity.Mongo.Stores.UserStore so we can provide our own implementation that inherit from it and initialize it the way we want.

Let me know if there are a way to do this

Thanks

**Comment by vova3211** [comment]
hey @martin-masse , don't know if it still relevant for you, but since [v9.0.0](https://www.nuget.org/packages/AspNetCore.Identity.Mongo/9.0.0) we are no longer force default indexes. Every situation is different, so it's up to you to decide how you handle indexes.
