### ISSUE TITLE
Using IdentityOptions.User.RequireUniqueEmail make register impossible

### ISSUE THREAD

**Issue by StephaneMartignier** [matteofabbri/AspNetCore.Identity.Mongo#12]
Hi,

First thanks for the great work, I use your project as a base and I made some additions.

Yesterday I try to set the IdentityOptions.User.RequireUniqueEmail = true; and I noticed that I was making register impossible.

I've made some digging and I found the following "bug":
When you choose this option, the UserManager from Identity It call the method ValidateUserAsync and this one call ValidateEmailAsync In UserValidator (I don't remember the exact sort of the calls).

The ValidateEmailAsync :

`

        private async Task ValidateEmail(UserManager<TUser> manager, TUser user, List<IdentityError> errors)
        {
            var email = await manager.GetEmailAsync(user);
            if (string.IsNullOrWhiteSpace(email))
            {
                errors.Add(Describer.InvalidEmail(email));
                return;
            }
            if (!new EmailAddressAttribute().IsValid(email))
            {
                errors.Add(Describer.InvalidEmail(email));
                return;
            }
            var owner = await manager.FindByEmailAsync(email);
            if (owner != null && 
                !string.Equals(await manager.GetUserIdAsync(owner), await manager.GetUserIdAsync(user)))
            {
                errors.Add(Describer.DuplicateEmail(email));
            }
        }

`

There is a call to manager.GetEmailAsync(user); (manager being the UserManager):

`        
public virtual async Task<string> GetEmailAsync(TUser user)
        {
            ThrowIfDisposed();
            var store = GetEmailStore();
            if (user == null)
            {
                throw new ArgumentNullException(nameof(user));
            }
            return await store.GetEmailAsync(user, CancellationToken);
        }
`

And in this one we call store.GetEmailAsync, and you implementation of this method is the following:

`

        public async Task<string> GetEmailAsync(TUser user, CancellationToken cancellationToken)
        {
            return (await _userCollection.FindByIdAsync(user.Id))?.Email;
        }

`

And since we are in registration the user is not yet in the DB, so the FindByIdAsync return null so the email is null, causing the validation to fail in ValidateEmail.

The Microsoft's implementation of the method GetEmailAsync:

`
        public virtual Task<string> GetEmailAsync(TUser user, CancellationToken cancellationToken = default(CancellationToken))
        {
            cancellationToken.ThrowIfCancellationRequested();
            ThrowIfDisposed();
            if (user == null)
            {
                throw new ArgumentNullException(nameof(user));
            }
            return Task.FromResult(user.Email);
        }

`

So when I change your implementation by the Microsoft's one it make the IdentityOptions.User.RequireUniqueEmail working.

So I think It's a bug? Or was it a purpose to this implementation?

By the way, it's the reason for the issue #7 

Waiting for your answer :)

Have a nice day

**Comment by matteofabbri** [comment]
Thanks a lot, I'm testing it, if I can i will upload it this evening <3
