### ISSUE TITLE
User collection is stored in "default" db when using replica set

### ISSUE THREAD

**Issue by Daviidbit** [matteofabbri/AspNetCore.Identity.Mongo#123]
While using a replica set, users collection is created in "default" db , not the related database. 
Even with the connection string set up to use replica sets, users are still stored in wrong database.

**Comment by vova3211** [comment]
hi @Daviidbit ,
could you provide connection string example that you are using? (omit private info)

**Comment by novecento** [comment]
I gettting now this "behaviour" after updating from 8.3.2 to 9.1.2.

my connstring is like:
"mongodb+srv://[username]:[password]@cluster0.fdkhg.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"
