### ISSUE TITLE
Is the project alive in the original repository?

### ISSUE THREAD

**Issue by xaberue** [matteofabbri/AspNetCore.Identity.Mongo#126]
Hi @matteofabbri !

First of all, thank you so much for sharing this amazing library with the community for free.

I wanted to know if you are already maintaining the project or not, since we need an upgrade to the latests SDK's, but seems there is no movement within this project.

I have successfully upgraded the project and will be happy to contribute sending a PR here; otherwise, if we cannot merge and publish from the original repo, we will try to get the baton and maintain a fork from our side.

Let me know.

Many thanks in advance!

**Comment by ziomek64** [comment]
I also require this

**Comment by matteofabbri** [comment]
Hi @xaberue 
Thank you very much for your interest and for writing to me.
The covid brought the apocalypse on me and my family, for years the wonderful collaborators took care of the project.
I had no idea that they too had abandoned it.
If you are still interested I can try to pick it up again.

**Comment by xaberue** [comment]
Hi @matteofabbri ,

Thanks for your reply back!

It saddens me to hear that, I'm sorry for the impact that the pandemic caused on your family and I hope that time has helped heal wounds.

About the project, I can raise a PR when I return back from my vacation, is that okay?

**Comment by matteofabbri** [comment]
Thanks to you, sure tnx
