### ISSUE TITLE
MissingFieldException for 'MongoDbContext' in AspNetCore.Identity.Mongo during Password Reset

### ISSUE THREAD

**Issue by lincolnqjunior** [matteofabbri/AspNetCore.Identity.Mongo#127]
**Describe the Bug:**
When attempting to reset a password using `userManager.ResetPasswordAsync` in a .NET application configured with `AspNetCore.Identity.Mongo`, an exception is raised indicating a missing field error: `Field not found: 'MongoDbGenericRepository.ReadOnlyMongoRepository`1.MongoDbContext'.`

**To Reproduce:**
1. Configure the application's identity services in `Program.cs` with the following settings:
```csharp
var mongoIdentityConfig = new MongoDbIdentityConfiguration
{
    MongoDbSettings = new MongoDbSettings() { ConnectionString = "your_connection_string", DatabaseName = "auth-db" },
    IdentityOptionsAction = options =>
    {
        options.Password.RequiredLength = 8;
        // Other options...
    }
};

services
    .ConfigureMongoDbIdentity<ApplicationUser, ApplicationRole, Guid>(mongoIdentityConfig)
    .AddMongoDbStores<ApplicationUser, ApplicationRole, Guid>("your_connection_string", "auth-db")
    .AddDefaultTokenProviders();
```
2. Execute the following test code:
```csharp
private async Task TestResetPassword()
{
    var user = await _userManager.FindByEmailAsync("existing@user.email");
    var token = await _userManager.GeneratePasswordResetTokenAsync(user);
    var result = await _userManager.ResetPasswordAsync(user, token, "NewPassword123!");
    if (result.Succeeded)
    {
        Console.WriteLine("Password reset succeeded.");
    }
    else
    {
        result.Errors.ToList().ForEach(error => Console.WriteLine($"Error: {error.Code} - {error.Description}"));
    }
}
```

**Expected behavior**
The password should be successfully reset without any exceptions.

**Screenshots**
![image](https://github.com/matteofabbri/AspNetCore.Identity.Mongo/assets/445449/3816c7c3-6b16-4d97-84ab-fec4958f306b)
![image](https://github.com/matteofabbri/AspNetCore.Identity.Mongo/assets/445449/f1f018bf-fc23-42bd-81df-61fdfe8b07e7)
![image](https://github.com/matteofabbri/AspNetCore.Identity.Mongo/assets/445449/6e814cc3-9c95-4cf6-9684-f352adfa1ef2)

**Environment:**
- Target framework: .NET 8.0
- MongoDB Driver Version: [2.25.0]
- AspNetCore.Identity.Mongo Version: [3.1.2]
- Operating System: [specify OS and version]
 - Dependencies: 
![image](https://github.com/matteofabbri/AspNetCore.Identity.Mongo/assets/445449/153f44d1-30b2-4189-8bda-3542ccb89b17)

**Comment by vova3211** [comment]
hi @lincolnqjunior , you are using different nuget package. Our is AspNetCore.Identity.Mongo and your is AspNetCore.Identity.Mongo**DbCore**.

You should open issue at [source repository](https://github.com/alexandre-spieser/AspNetCore.Identity.MongoDbCore/issues) or you can try our library instead, following instructions in the [How to use](https://github.com/matteofabbri/AspNetCore.Identity.Mongo?tab=readme-ov-file#how-to-use) section
