### ISSUE TITLE
The build issue that occurs after updating the MongoCSharpDriver

### ISSUE THREAD

**Issue by SteAmeR** [matteofabbri/AspNetCore.Identity.Mongo#129]
**Describe the bug**
An error occurred when updating from mongocharpdriver-2.27 to 2.28 as below;

CS0012	The type 'ObjectId' is defined in an assembly that is not referenced. You must add a reference to assembly 'MongoDB.Bson, Version=2.13.2.0, Culture=neutral, PublicKeyToken=null'

**To Reproduce**
1. Go to 'Nuget Update'
2. Click on 'MongoCSharpDriver 2.28.0'

**Expected behavior**
As before, we expect it to work in concert without any problems.

**Screenshots**

**Environment (please complete the following information):**
 - .Net Core version: [.Net Core 8.0]
 - Package Version: [8.3.3]

**Comment by garethrampton** [comment]
Same issue. Just discovered this.

**Comment by vova3211** [comment]
hi there, next versions has fixed this issue:
[v8.3.5](https://www.nuget.org/packages/AspNetCore.Identity.Mongo/8.3.5)
[v9.0.0](https://www.nuget.org/packages/AspNetCore.Identity.Mongo/9.0.0)

@SteAmeR  v9.0.0 supports Net8, so I advice you to upgrade to this version directly instead of 8.3.5
