### ISSUE TITLE
Roles and Authorize Filter

### ISSUE THREAD

**Issue by akluthe** [matteofabbri/AspNetCore.Identity.Mongo#13]
Role checks and Authorize filters don't seem to work with .NET Core 2.2 projects.

Related to this?
https://github.com/aspnet/Identity/issues/1813#issuecomment-394466269

I am going to try and solve it, but any help getting pointed in the right direction would be wonderful.

**Comment by matteofabbri** [comment]
Ehm, this is complicated, I'm trying to work on it.
Thanks a lot

**Comment by matteofabbri** [comment]
@akluthe looks fixed now. Also latest package is updated to 2.2 
Let me know :)

**Comment by Coz1178** [comment]
Does this work with the latest version?  What is the configuration needed to make it work?  I haven't been able to get the [Authorize] attribute working in any form, even after I successfully sign in.
