### ISSUE TITLE
E-mail sender service not registered by default

### ISSUE THREAD

**Issue by filipbekic01** [matteofabbri/AspNetCore.Identity.Mongo#130]
On fresh .NET 8 (latest), runtime throws error:

`System.InvalidOperationException: No service for type 'Microsoft.AspNetCore.Identity.IEmailSender1[Resqueue.Models.User]' has been registered.`

Technically I can solve this by adding dummy email sender implementation:

```C#
using Microsoft.AspNetCore.Identity;
using MyApp.Models;

namespace MyApp;

public class DummyEmailSender : IEmailSender<User>
{
    public Task SendConfirmationLinkAsync(User user, string email, string confirmationLink)
    {
        return Task.CompletedTask;
    }

    public Task SendPasswordResetLinkAsync(User user, string email, string resetLink)
    {
        return Task.CompletedTask;
    }

    public Task SendPasswordResetCodeAsync(User user, string email, string resetCode)
    {
        return Task.CompletedTask;
    }
}

// ...

builder.Services.AddSingleton<IEmailSender<User>, DummyEmailSender>();
```

This works well but should there be default implementation to make setup easier? Just curious if this is bug or not.

**Comment by vova3211** [comment]
@filipbekic01 I believe you have enabled two factor authentication or something like that, and you have to provide your own `IEmailSender` implementation. Library provides implementation only for the User/Role Stores

if you still have questions feel free to reopen issue.
