### ISSUE TITLE
AddIdentityMongoDbProvider throw "Must contain at least 1 request" (v8.3.4. mongodbdriver 2.28.0)

### ISSUE THREAD

**Issue by lufo88ita** [matteofabbri/AspNetCore.Identity.Mongo#132]
**Describe the bug**
When call "AddIdentityMongoDbProvider" in startup it rise the exception 
"Must contain at least 1 request"

**To Reproduce**

I run this code:
```
services.AddIdentityMongoDbProvider<ApplicationUser, ApplicationRole>(identityOptions =>
{
    identityOptions.Password.RequiredLength = 8;
    identityOptions.Password.RequireLowercase = true;
    identityOptions.Password.RequireUppercase = true;
    identityOptions.Password.RequireNonAlphanumeric = true;
    identityOptions.Password.RequireDigit = true;

    identityOptions.User.RequireUniqueEmail = true;
}, mongoIdentityOptions =>
{
    mongoIdentityOptions.ConnectionString = <connectionString>;
    mongoIdentityOptions.UsersCollection = "users";
    mongoIdentityOptions.RolesCollection = "roles";
});
```
In my startup.cs and it throw the exception right away.

**Expected behavior**
No exception rise

**Environment (please complete the following information):**
 - .Net Core version: 6.0
 - Package Version:  8.3.4
- Mongo db driver version 2.28.0

**Additional context**
With version 8.3.3 and mongo driver 2.27.0 the exception is not rised.

**Comment by vova3211** [comment]
hi @lufo88ita , we are aware of this issue. I'm going to publish new version in the next hour.

**Comment by vova3211** [comment]
[version 8.3.5](https://www.nuget.org/packages/AspNetCore.Identity.Mongo/8.3.5) is available.
