### ISSUE TITLE
_id format backward compatibility

### ISSUE THREAD

**Issue by sbrosgol** [matteofabbri/AspNetCore.Identity.Mongo#15]
In version 3.1.5 the _id (in user and role stores) format was like the following:
"_id" : ObjectId("5c5fea3a39580f24c8598b59"),

However, in version 5.0.0.12, the format was changed. This caused exceptions after a nuget package update.

**Comment by matteofabbri** [comment]
Yes, sadly the only solution is to run a migration script.
But the new format will not change again in future
