### ISSUE TITLE
Can you set target framework for your library to netstandart2.0?

### ISSUE THREAD

**Issue by ygrinevich** [matteofabbri/AspNetCore.Identity.Mongo#18]
Hi,

I'd like a reference your library from netstandard2.0 library. But I can't do it now because it targets netcoreapp2.2

**Comment by malachib** [comment]
Just hit this myself.  +1

**Comment by matteofabbri** [comment]
Not sure about that due to references of aspnet core base interfaces.
But i will check tomorrow morning and if is possible sure :) 
Thanks a lot :)

**Comment by matteofabbri** [comment]
fixed by @malachib PR :)
