### ISSUE TITLE
Using beta MongoDb.Driver

### ISSUE THREAD

**Issue by rafaeldruiz** [matteofabbri/AspNetCore.Identity.Mongo#22]
I'm receiving the below error when trying to update AspNetCore.Identity.Mongo nuget package:

Severity	Code	Description	Project	File	Line	Suppression State
Error	NU1605	Detected package downgrade: MongoDB.Driver from 2.9.0-beta1 to 2.8.0. Reference the package directly from the project to select a different version. 
 Infra.Data.MongoDb -> AspNetCore.Identity.Mongo 5.1.0.15 -> MongoDB.Driver (>= 2.9.0-beta1) 
 Infra.Data.MongoDb -> MongoDB.Driver (>= 2.8.0)	Infra.Data.MongoDb	C:\MyProjects\Nira\source\Infra\Data\MongoDb\Infra.Data.MongoDb\Infra.Data.MongoDb.csproj	1	

I do not want to use beta drivers on my project. Can you reference a stable version?

Thanks.

**Comment by matteofabbri** [comment]
Fixed :)
