### ISSUE TITLE
dotnet core 3.0 support

### ISSUE THREAD

**Issue by JorundMartinsen** [matteofabbri/AspNetCore.Identity.Mongo#23]
Now that .net core 3.0 has been released, will it be supported by this package?

**Comment by Coz1178** [comment]
I tried it and was getting grief on the CreateAsync method, yet it was writing to the database.  Followed the stack trace back to UserStore.SetEmailAsync.  Changed

`await SetNormalizedEmailAsync(user, _normalizer.Normalize(user.Email), cancellationToken);`

to

`await SetNormalizedEmailAsync(user, _normalizer.NormalizeEmail(user.Email), cancellationToken);`

And all seems well... so far.  I'm hoping changes to the identity framework between 2.x and 3.0 were minor enough to limit things to this one instance.

**Comment by JorundMartinsen** [comment]
Which branch is this?

**Comment by matteofabbri** [comment]
>  will it be supported by this package? 
In theory yes, but I'm not sure on how, because upgraded to 3.0 it would be not more referenced by 2.2

@Coz1178 is this connected to #24 ?

**Comment by JorundMartinsen** [comment]
This is covered in #24

**Comment by matteofabbri** [comment]
@JorundMartinsen  @Coz1178 

Fixed in latest commit https://github.com/matteofabbri/AspNetCore.Identity.Mongo/commit/fe20430be99363da580c10cc8c2f2074fcebcbd4

It require some testing than i will make the nuget :) 
Tnx
