### ISSUE TITLE
Method not found: System.String Microsoft.AspNetCore.Identity.ILookupNormalizer.Normalize(System.String)

### ISSUE THREAD

**Issue by alidehghan** [matteofabbri/AspNetCore.Identity.Mongo#24]
After updating to core 3, the method **AspNetCore.Identity.Mongo.Stores.UserStore`2.SetEmailAsync(TUser user, String email, CancellationToken cancellationToken)** throws exception : **Method not found: System.String Microsoft.AspNetCore.Identity.ILookupNormalizer.Normalize(System.String)**

**Comment by matteofabbri** [comment]
Yep, found the same problem after installing the package on a .net core 3 project.
Will start the fix today, together with the upgrade to 3.0.
Thanks

**Comment by matteofabbri** [comment]
@alidehghan  


Fixed in latest commit https://github.com/matteofabbri/AspNetCore.Identity.Mongo/commit/fe20430be99363da580c10cc8c2f2074fcebcbd4

It require some testing than i will make the nuget :) 
Tnx

**Comment by alidehghan** [comment]
Many thanks for your nice job ... when do we expect it to be available on nuget?

**Comment by matteofabbri** [comment]
6.0.0 published 4 days ago
