### ISSUE TITLE
Incompatible with dotnet core 2.2

### ISSUE THREAD

**Issue by dmradford** [matteofabbri/AspNetCore.Identity.Mongo#25]
Attempting to upgrade from AspNetCore.Identity.Mongo version 5.2.1 to version 6.0.0, received the following error:

```
error: Package AspNetCore.Identity.Mongo 6.0.0 is not compatible with netcoreapp2.2 (.NETCoreApp,Version=v2.2). Package AspNetCore.Identity.Mongo 6.0.0 supports: netstandard2.1 (.NETStandard,Version=v2.1)
error: Package 'AspNetCore.Identity.Mongo' is incompatible with 'all' frameworks in project 'C:\.....\.....\project.csproj'.
```

Upgrading the project to netcoreapp3.0 resolves the issue, however this is not possible for many people who rely on legacy packages that have not yet been updated to support dotnet core 3.0.

**Comment by matteofabbri** [comment]
yep, i will do a package 5.something with all new fixed but with all references

**Comment by stevensotelo** [comment]
Hi @matteofabbri 

Thanks to build this package, actually I upgraded one website to .net core 2.2 and it is the only good packages that I could find.

I wanna know if you could solve this issue, because I have legacy system that I couldn't update and I think that a set of issues that I found, which have been solved in the new version.

Thanks.

**Comment by matteofabbri** [comment]
@stevensotelo  @dmradford fixed in https://www.nuget.org/packages/AspNetCore.Identity.Mongo/5.1.0.17

**Comment by matteofabbri** [comment]
Core 2.2 will now live in branch https://github.com/matteofabbri/AspNetCore.Identity.Mongo/tree/CORE22

**Comment by stevensotelo** [comment]
It is a little strange the version that you have in nuget. Which one is the latest and stable version?
 
![image](https://user-images.githubusercontent.com/4921829/68246590-1799e280-ffe7-11e9-8072-5973c6cd70a1.png)

**Comment by matteofabbri** [comment]
@stevensotelo 6.1.1 is the latest for dotnet core 3.0, 5.1.0.17 is 2.2 
I just realised i fucked up the numeration for the old version, thanks for the warning
