### ISSUE TITLE
FindByEmailAsync always return null

### ISSUE THREAD

**Issue by sergey-messer** [matteofabbri/AspNetCore.Identity.Mongo#26]
FindByEmailAsync always return null
The bug is in UserStore.cs:
```
public async Task<TUser> FindByEmailAsync(string normalizedEmail, CancellationToken cancellationToken)
{
   cancellationToken.ThrowIfCancellationRequested();
   return await ById(normalizedEmail);
}

```
Using ById(normalizedEmail) function is wrong

In preview version was:

```
public async Task<TUser> FindByEmailAsync(string normalizedEmail, CancellationToken cancellationToken)
{
    cancellationToken.ThrowIfCancellationRequested();
    return await _userCollection.FindByEmailAsync(normalizedEmail);
}

```

**Comment by matteofabbri** [comment]
Thanks a lot :) fixed in https://github.com/matteofabbri/AspNetCore.Identity.Mongo/pull/27

**Comment by mcbaloo** [comment]
I am trying to save user record but I also noticed that NormalizedEmail is null in my MongoCollection after saving the record. What could be the cause?
