### ISSUE TITLE
Your website is not working

### ISSUE THREAD

**Issue by programad** [matteofabbri/AspNetCore.Identity.Mongo#28]
Hi, man, I didn't know how to contact you so I am opening an issue here.

Your website is down!

I am planing to use your ASPNETCore.Identity.Mongo implementation and I want to make sure I can contact youto improve the packages based on the challenge I will face this month.

**Comment by matteofabbri** [comment]
@programad sure :) 
the website is down on purpose because it was quite empty, you need some help ?

**Comment by programad** [comment]
Oh, ok.

I could use some help. maybe. I am trying to understand and adapt your
solution for identity mongodb to my opensource project. So far I could not
get it to run correctly but I am taking baby steps. I am just a little
afraid I will lose something since I am migrating from an official
Microsoft SQL with Entity Framework solution and I didn't notice the
Password option on the MongoIdentityOptions on your solution.

Anyway, thank you for your great solution.
[image: Microsoft Certified Professional]

  Daniel Gomes
+55 13 99122 4519
