### ISSUE TITLE
How does the authorization work?

### ISSUE THREAD

**Issue by stevensotelo** [matteofabbri/AspNetCore.Identity.Mongo#29]
Hi @matteofabbri 

Currently, I'm trying to implement the authorization (decorator) in my website, but it is not working in normal way. I have the following code in a controller:

// GET: /Controller/Index
[HttpGet]
[Authorize(Roles = "ADMIN")]
public async Task<IActionResult> Index()
{
     return View();
}

The user in the database has the role ADMIN:

![image](https://user-images.githubusercontent.com/4921829/68487494-28c63780-0211-11ea-9088-a509097a259f.png)

However, always that I'm trying to get into this action, the controller has redirected me to DeniedAccess webpage

**Comment by matteofabbri** [comment]
That really looks like an old version, which package are you using ? 
Also: core 3 or 2.2 ?

**Comment by stevensotelo** [comment]
I'm using .net core 2.2 and package version 5.1.0.17

**Comment by matteofabbri** [comment]
There was a bug, has been fixed. 
5.3 with the fix will be available in minutes
