### ISSUE TITLE
How to set _id of type ObjectId

### ISSUE THREAD

**Issue by chandrakantnaik789** [matteofabbri/AspNetCore.Identity.Mongo#33]
How to set _id of type ObjectId

**Comment by dmradford** [comment]
```
public partial class Base
    {
        [BsonId]
        [BsonRepresentation(BsonType.ObjectId)]
        public string Id { get; set; }

        public string UserId { get; set; }

        public DateTime CreateDate { get; set; }

        public DateTime ModifyDate { get; set; }
    }
```

**Comment by chandrakantnaik789** [comment]
I actually want to set _Id of IdentityUser to ObjectId but i think its by default support guid in string format

**Comment by chandrakantnaik789** [comment]
> Using Bson.Serialization.Attributes and an annotation. See example below:
> 
> ```
> using MongoDB.Bson;
> using MongoDB.Bson.Serialization.Attributes;
> 
> public partial class Base
>     {
>         [BsonId]
>         [BsonRepresentation(BsonType.ObjectId)]
>         public string Id { get; set; }
> 
>         public string UserId { get; set; }
> 
>         public DateTime CreateDate { get; set; }
> 
>         public DateTime ModifyDate { get; set; }
>     }
> ```

I know it. But how to do it for IdentityUser

**Comment by dmradford** [comment]
It looks like using objectId for ApplicationUser _id may not be easily doable. I just tried overriding the property and got this error:

> 'The property 'Id' of type 'FinanceForecaster.DataAccess.Model.Identity.ApplicationUser' cannot use element name '_id' because it is already being used by property 'Id' of type 'Microsoft.AspNetCore.Identity.IdentityUser`1[[System.String, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]'.'

Basically, as I understand it, since Microsoft.AspNetCore.Identity.IdentityUser doesnt use ObjectId and uses a guid instead, you can only use the auto generated guid.

This shouldn't be much of an issue though, since users are rarely looked up by id, but rather by email or other properties. What are you trying to do that requires the id to be an ObjectId?

**Comment by chandrakantnaik789** [comment]
> It looks like using objectId for ApplicationUser _id may not be easily doable. I just tried overriding the property and got this error:
> 
> > 'The property 'Id' of type 'App.DataAccess.Model.Identity.ApplicationUser' cannot use element name '_id' because it is already being used by property 'Id' of type 'Microsoft.AspNetCore.Identity.IdentityUser`1[[System.String, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]'.'
> 
> Basically, as I understand it, since Microsoft.AspNetCore.Identity.IdentityUser doesnt use ObjectId and uses a guid instead, you can only use the auto generated guid.
> 
> This shouldn't be much of an issue though, since users are rarely looked up by id, but rather by email or other properties. What are you trying to do that requires the id to be an ObjectId?

I already have existing database where I have users with _id as objectid and i want to migrate it to 
AspNetCore.Identity.Mongo library and i also have many other table dependencies to _id column

**Comment by dmradford** [comment]
Ah, that makes sense. It looks like you're going to have to extend and override the builtin properties and maybe some of the methods for Microsoft.AspNetCore.Identity.IdentityUser

This may be of use:
https://adrientorris.github.io/aspnet-core/identity/extend-user-model.html

**Comment by chandrakantnaik789** [comment]
I use other library to resolve my issue
