### ISSUE TITLE
UserManager.SetAuthenticationTokenAsync does not persist changes

### ISSUE THREAD

**Issue by 7Kronos** [matteofabbri/AspNetCore.Identity.Mongo#34]
Updated the library from my last fork to the last nuget version and my failed tests show that UserManager.SetAuthenticationTokenAsync does not persist tokens in database anymore.

I used a temporary workaround mutating the tokens list and then calling UserManager.UpdateAsync whitch works fine.

Did not have the time to investigate this.

**Comment by matteofabbri** [comment]
thanks just fixed, publishing packet now.
