### ISSUE TITLE
UserManager.GenerateEmailConfirmationTokenAsync does not persist token

### ISSUE THREAD

**Issue by abirstolov** [matteofabbri/AspNetCore.Identity.Mongo#37]
I'm using the following method:
`var token = await _userManager.GenerateEmailConfirmationTokenAsync(user);`
And it returns a token, but nothing is written to the user document, the Tokens array is empty.

The service setup:
```csharp
services.AddIdentityMongoDbProvider<ApplicationUser, ApplicationRole>(options =>
            {
                options.Password.RequiredLength = 6;
                options.Password.RequireLowercase = false;
                options.Password.RequireUppercase = false;
                options.Password.RequireDigit = false;
                options.Password.RequireNonAlphanumeric = false;
                options.SignIn.RequireConfirmedEmail = true;
            }, mongoIdentityOptions => 
            {
                mongoIdentityOptions.ConnectionString = "mongodb://localhost:27017";
            });
```

**Comment by vova3211** [comment]
Hi @abirstolov , if go inside `AddIdentityMongoDbProvider` you can see that this lib doesn't implement/override TokenProvider's and just use default `AddDefaultTokenProviders` method:
`builder.AddRoleStore<RoleStore<TRole>>()
.AddUserStore<UserStore<TUser, TRole>>()
.AddUserManager<UserManager<TUser>>()
.AddRoleManager<RoleManager<TRole>>()
.AddDefaultTokenProviders();`

If we look at `GenerateEmailConfirmationTokenAsync` in `UserManager` => it's just call of `GenerateAsync` method `IUserTwoFactorTokenProvider` provider, which is `DataProtectorTokenProvider` according to `IdentityBuilderExtensions` [link](https://github.com/dotnet/aspnetcore/blob/master/src/Identity/Core/src/IdentityBuilderExtensions.cs#L24)

[DataProtectorTokenProvider] are not saving any info to user.(https://github.com/dotnet/aspnetcore/blob/master/src/Identity/Core/src/DataProtectorTokenProvider.cs#L82)

You can implement your own `IUserTwoFactorTokenProvider` and add it like:
`services.AddIdentityMongoDbProvider<ApplicationUser, ApplicationRole>(options =>
            {
                options.Password.RequiredLength = 6;
                options.Password.RequireLowercase = false;
                options.Password.RequireUppercase = false;
                options.Password.RequireDigit = false;
                options.Password.RequireNonAlphanumeric = false;
                options.SignIn.RequireConfirmedEmail = true;
            }, mongoIdentityOptions =>
            {
                mongoIdentityOptions.ConnectionString = "mongodb://localhost:27017";
            })
            .AddTokenProvider<MyUserTwoFactorTokenProvider<ApplicationUser>>(TokenOptions.DefaultProvider);`

Where `MyUserTwoFactorTokenProvider<ApplicationUser>` is implementation of `IUserTwoFactorTokenProvider<TUser>`.

**Comment by matteofabbri** [comment]
Does it have sense to add this in the library ? im undecided

**Comment by vova3211** [comment]
@matteofabbri What the point to override default token provider?
You can add your own implementation of `IUserTwoFactorTokenProvider<TUser>` through `AddTokenProvider()` at any moment.
