### ISSUE TITLE
Role Claims Support using Identity framework with Mongo

### ISSUE THREAD

**Issue by haseeb200** [matteofabbri/AspNetCore.Identity.Mongo#38]
I wonder if one can tell me how to add role claims? because I am unable to find any implementation regarding this.

How shall I assign claim to specific role?

when ever I try to add claims for role I received following error

![image](https://user-images.githubusercontent.com/10439778/76880557-a4a84e80-6899-11ea-894e-430da34ceb53.png)

**Comment by dmradford** [comment]
The way I have it configured is as follows:

In Startup.cs, use AddAuthorization to add the roles for auth:

```
services.AddAuthorization(options =>
            {
                options.AddPolicy("Administrator", policy => policy.RequireRole("Admin"));
                options.AddPolicy("Standard", policy => policy.RequireRole("Standard"));
            });
```

On your controllers, use the Authorize annotation:

```
        [Authorize(Roles = "Administrator")]
        [HttpGet]
        public async Task<ActionResult> UserData()
        {
            var user = await _userManager.GetUserAsync(User);
            var userData = new UserDataResponse
            {
                Name = user.UserName,
                LastName = user.LastName,
                City = user.City,
                Email = user.Email
            };
            return Ok(userData);
        }
```

Then last but not least, create roles and add users to them. For testing you can (need to) have these as non-authorized routes but you'll have to lock this down before going live obviously:

```
        [HttpPost]
        [AllowAnonymous]
        /// <summary>
        /// Create Role in DB
        /// </summary>
        public async Task<IActionResult> RegisterRole([FromBody]string roleName)
        {
            // Create admin role
            var role = new ApplicationRole();
            role.Name = roleName;
            var result = await _roleManager.CreateAsync(role);

            return Ok(result.Succeeded);
        }

        [HttpPost]
        [AllowAnonymous]
        /// <summary>
        /// Add logged in user to role by role name (string)
        /// </summary>
        public async Task<IActionResult> AddUserRole([FromBody]string roleName) 
        {
            var user = await _userManager.GetUserAsync(User);
            var result = await _userManager.AddToRoleAsync(user, roleName);

            return Ok(result.Succeeded);
        }
```

**Comment by haseeb200** [comment]
that's all clear t me. My question is regarding adding Claims for role. If you follow the identity pattern they have Claims for user and then Claims for Role as well. SO i want to know how to use Role Claims rather than User Claims?

**Comment by vova3211** [comment]
@matteofabbri I guess, `AspNetCore.Identity.Mongo.Stores.RoleStore<TRole>` should implement interface `IRoleClaimStore<TRole>`.
Same as it's now implementing interface `IQueryableRoleStore<TRole>`. Both interfaces inherited from `IRoleStore<TRole>` and used in `RoleManager<TRole>`
Also attaching link to source file of   [https://github.com/dotnet/aspnetcore/blob/master/src/Identity/Extensions.Core/src/RoleManager.cs#L462](`RoleManager<TRole>`)

I can create pull request for it. Will it be useful?

**Comment by vova3211** [comment]
@haseeb200 Oh you already did it, sorry)
So this issue can be closed?

**Comment by matteofabbri** [comment]
im gonna publish the package with the change now. thanks a lot for the PR
