### ISSUE TITLE
Use with Blazor?

### ISSUE THREAD

**Issue by leandromendes-ifthen** [matteofabbri/AspNetCore.Identity.Mongo#40]
Hey! Is it possible to use this package with blazor? im quite new to asp.net/asp.net core stuff and i would like no know if it works with it. Its only needed to include  the wiki code ?

What about the class ApplicationUser and ApplicationRole where and what should i include on them. An example would be great , thanks!

**Comment by matteofabbri** [comment]
Hi :) honestly i have no idea, i never used Blazor, but i will try and let you now :)

**Comment by leandromendes-ifthen** [comment]
Thank you, from my research you are the only ative developer mantaining Identity for mongo. Keep up the good work. And please let me know what should the ApplicationUser and ApplicationRole should contain so i can test in my side.

**Comment by BuzzDee3000** [comment]
@leandromendes-ifthen 
You can use this package in blazor the same way like in other asp.net core apps.
The base classes for users and roles are MongoUser and MogoRole. That can be used directly or you can create you own that inherits from them.

**Comment by leandromendes-ifthen** [comment]
Im using the default classes directly MongoUser and MogoRole, but im unable to navigate to register and login page of the base identity on Blazor. I am doing something wrong or these need their own implementation?  i just want to reuse the existing ui but with mongo

**Comment by BuzzDee3000** [comment]
@leandromendes-ifthen 
I have created a simple solution from the default blazor project template and replaced the sqlite provider with mongo.
https://github.com/BuzzDee3000/AspNetCoreBlazorWithMongoIdentitySample

The point is to check the dependency injection and replace all IdentityUser with MongoUser.
`UserManager<IdentityUser`
must replaced with
`UserManager<MongoUser>`

You have to do the same when you are using customized identity classes independent from the identity storage.

**Comment by leandromendes-ifthen** [comment]
@BuzzDee3000 
Thank you so much ! Really kind of you! This is enough to keep me going and what i needed. 
You should consider doing a "full port" on your own or add a full sample as contribution for this project.
Keep up the good work!

**Comment by leandromendes-ifthen** [comment]
@BuzzDee3000 how can you scaffold the remaining files in blazor? should i select my _host.cshtml, since blazor doesnt use _layout.cshtml.  Everything i do to add the remaining classes results on exceptions or other view/ui of the project not related to identity to be messed up

**Comment by BuzzDee3000** [comment]
@leandromendes-ifthen 
Can you provide some code or exception messages?

**Comment by vova3211** [comment]
@leandromendes-ifthen is your problem solved? This issue frozen almost month, so i closed it.
If you'll have any other questions you can ask and reopen issue.
