### ISSUE TITLE
Save _id as "ObjectId" instead of "String"

### ISSUE THREAD

**Issue by fernandocerkal** [matteofabbri/AspNetCore.Identity.Mongo#41]
Folks,
After migration from 3.1.5 (with .net core 2.1) to 6.3.5 (with .net core 3.1), the object has been saved as "String" instead of "ObjectId".

I tried without success override Id property, althought it saves two "Ids" in collection.

Startup:

   ```
services.AddIdentityMongoDbProvider<ApplicationUser, ApplicationRole>(identityOptions =>
            {
                identityOptions.Password.RequiredLength = 6;
                identityOptions.Password.RequireLowercase = true;
                identityOptions.Password.RequireUppercase = true;
                identityOptions.Password.RequireNonAlphanumeric = true;
                identityOptions.Password.RequireDigit = true;
            }, mongoIdentityOptions => {
                mongoIdentityOptions.ConnectionString = Configuration.GetConnectionString("MongoDbDatabase");
            });
```

ApplicationUser:
private string _id;
    
        [BsonRepresentation(BsonType.ObjectId)]
        public override string Id { 
            get { return this._id;}
            set
            {
                ObjectId result;
                if (!ObjectId.TryParse(value, out result))
                    value = ObjectId.GenerateNewId().ToString();
                this._id = value;
            } 
        } 

Startup:

Data:
`{
    "_id" : "5e855b9506cf7b1818579dce",
    "UserName" : "fernando@cerkal.com.br",
    "NormalizedUserName" : "FERNANDO@CERKAL.COM.BR",
    "Email" : "fernando@cerkal.com.br",
    "NormalizedEmail" : "FERNANDO@CERKAL.COM.BR",
    "EmailConfirmed" : false,
    "PasswordHash" : "AQAAAAEAACcQAAAAEJrg3Xf5Yw3ss8zFwtOhYG3ln/gHIvhrVZg+y4ZH4c6Wt0kvmY9LAvZk5X9FDEqkLw==",
    "SecurityStamp" : "ET5JPIOZ7PL4I4433MSEWCY3HXZEVFZL",
    "ConcurrencyStamp" : "3dbf8453-109e-443d-888f-cdf06d34a260",
    "PhoneNumber" : "21995555555",
    "PhoneNumberConfirmed" : false,
    "TwoFactorEnabled" : false,
    "LockoutEnd" : null,
    "LockoutEnabled" : true,
    "AccessFailedCount" : 0,
    "AuthenticatorKey" : null,
    "Roles" : [ 
        "partner"
    ],
    "Claims" : [],
    "Logins" : [],
    "Tokens" : [],
    "RecoveryCodes" : [],
    "Name" : "Luiz",
    "FacebookId" : NumberLong(0),
    "PictureUrl" : null,
    "BirthDate" : ISODate("2000-03-26T23:59:59.999Z"),
    "RegNumber" : "05775741856",
    "ActivateNumbers" : "145586",
    "Id" : ObjectId("5e855b9506cf7b1818579dce")
}`

**Comment by vova3211** [comment]
@fernandocerkal nuget package was recently updated and added support for ObjectId. Please update your version to 6.7.0
