### ISSUE TITLE
Support for IdentityServer4.IdentityServerConstants.ClaimValueTypes.Json deserialization

### ISSUE THREAD

**Issue by alecrt** [matteofabbri/AspNetCore.Identity.Mongo#46]
Dear Matteo,

is it possibile to support IdentityServer4.IdentityServerConstants.ClaimValueTypes.Json object deserialization?

For example we'd like to store address as complex object (or json) claim, like below:
`new Claim(JwtClaimTypes.Address, @"{ 'street_address': 'One Hacker Way', 'locality': 'Heidelberg', 'postal_code': 69118, 'country': 'Germany' }", IdentityServer4.IdentityServerConstants.ClaimValueTypes.Json)`

But when we get the user from UserManager and pass it through ActionResult API endpoint it's still a string and not a json object.

Thank you!
Alessandro

**Comment by vova3211** [comment]
Hi @alecrt!
What you trying to achieve? This lib is wrapper for ASP.NET Core Identity and doesn't responsible for any claim conversions etc.
As i understood correctly, you want use `JwtClaimTypes.Address` like object. According to official [docs](https://docs.microsoft.com/en-us/dotnet/api/system.security.claims.claim?view=netframework-4.8) Claim can contains only string value. If you want to use more complex type than string you should check it on `ValueType` field and than decide what to do with it.

Also i checked IdentityServer4 example [repository](https://github.com/IdentityServer/IdentityServer4.Demo) and added to watch claims. As you can see on screens the `Value` still string, but you can identify it by `ValueType` and convert.
![watch_ids4_demo](https://user-images.githubusercontent.com/24604802/79864410-19633100-83e2-11ea-81ea-4f1ae55296de.png)

Please follow the link which i mentioned before to official docs - it has a lot of explanation about Claims.
