### ISSUE TITLE
v6.7.0 ObjectId Error

### ISSUE THREAD

**Issue by sayron5** [matteofabbri/AspNetCore.Identity.Mongo#49]
Hi,

I noticed an issue with signing in once I upgraded from version 6.3.5 to 6.7.0.  There seems to be a ObjectID -> String conversion issue using the updated version.  I am running this test using a Blazor Server application so it may work in other project types:

An unhandled exception occurred while processing the request.
FormatException: 'dbf7a32a-3ca3-4525-a734-b82d61024e82' is not a valid 24 digit hex string.
MongoDB.Bson.ObjectId.Parse(string s)

FormatException: An error occurred while deserializing the Id property of class Microsoft.AspNetCore.Identity.IdentityUser`1[[MongoDB.Bson.ObjectId, MongoDB.Bson, Version=2.10.2.0, Culture=neutral, PublicKeyToken=null]]: 'dbf7a32a-3ca3-4545-a704-b82d61024e82' is not a valid 24 digit hex string.

FormatException: An error occurred while deserializing the Id property of class Microsoft.AspNetCore.Identity.IdentityUser`1[[MongoDB.Bson.ObjectId, MongoDB.Bson, Version=2.10.2.0, Culture=neutral, PublicKeyToken=null]]: 'dbf7a32a-3ca3-4525-a734-b82d61024e82' is not a valid 24 digit hex string.
MongoDB.Bson.Serialization.BsonClassMapSerializer<TClass>.DeserializeMemberValue(BsonDeserializationContext context, BsonMemberMap memberMap)
MongoDB.Bson.Serialization.BsonClassMapSerializer<TClass>.DeserializeClass(BsonDeserializationContext context)
MongoDB.Bson.Serialization.BsonClassMapSerializer<TClass>.Deserialize(BsonDeserializationContext context, BsonDeserializationArgs args)
MongoDB.Bson.Serialization.IBsonSerializerExtensions.Deserialize<TValue>(IBsonSerializer<TValue> serializer, BsonDeserializationContext context)
MongoDB.Driver.Core.Operations.CursorBatchDeserializationHelper.DeserializeBatch<TDocument>(RawBsonArray batch, IBsonSerializer<TDocument> documentSerializer, MessageEncoderSettings messageEncoderSettings)
MongoDB.Driver.Core.Operations.FindCommandOperation<TDocument>.CreateCursorBatch(BsonDocument commandResult)
MongoDB.Driver.Core.Operations.FindCommandOperation<TDocument>.CreateCursor(IChannelSourceHandle channelSource, BsonDocument commandResult)
MongoDB.Driver.Core.Operations.FindCommandOperation<TDocument>.ExecuteAsync(RetryableReadContext context, CancellationToken cancellationToken)
MongoDB.Driver.Core.Operations.FindOperation<TDocument>.ExecuteAsync(RetryableReadContext context, CancellationToken cancellationToken)
MongoDB.Driver.Core.Operations.FindOperation<TDocument>.ExecuteAsync(IReadBinding binding, CancellationToken cancellationToken)
MongoDB.Driver.OperationExecutor.ExecuteReadOperationAsync<TResult>(IReadBinding binding, IReadOperation<TResult> operation, CancellationToken cancellationToken)
MongoDB.Driver.MongoCollectionImpl<TDocument>.ExecuteReadOperationAsync<TResult>(IClientSessionHandle session, IReadOperation<TResult> operation, ReadPreference readPreference, CancellationToken cancellationToken)
MongoDB.Driver.MongoCollectionImpl<TDocument>.UsingImplicitSessionAsync<TResult>(Func<IClientSessionHandle, Task<TResult>> funcAsync, CancellationToken cancellationToken)
AspNetCore.Identity.Mongo.MongoUtil.FirstOrDefaultAsync<TItem>(IMongoCollection<TItem> mongoCollection, Expression<Func<TItem, bool>> p)
Microsoft.AspNetCore.Identity.UserManager<TUser>.FindByNameAsync(string userName)
Microsoft.AspNetCore.Identity.SignInManager<TUser>.PasswordSignInAsync(string userName, string password, bool isPersistent, bool lockoutOnFailure)
Microsoft.AspNetCore.Identity.UI.V4.Pages.Account.Internal.LoginModel<TUser>.OnPostAsync(string returnUrl)
Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.ExecutorFactory+GenericTaskHandlerMethod.Convert<T>(object taskAsObject)
Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.ExecutorFactory+GenericTaskHandlerMethod.Execute(object receiver, object[] arguments)
Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.PageActionInvoker.InvokeHandlerMethodAsync()
Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.PageActionInvoker.InvokeNextPageFilterAsync()
Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.PageActionInvoker.Rethrow(PageHandlerExecutedContext context)
Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.PageActionInvoker.Next(ref State next, ref Scope scope, ref object state, ref bool isCompleted)
Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.PageActionInvoker.InvokeInnerFilterAsync()
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, object state, bool isCompleted)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(ref State next, ref Scope scope, ref object state, ref bool isCompleted)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, object state, bool isCompleted)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.MigrationsEndPointMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.Invoke(HttpContext httpContext)
Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.Invoke(HttpContext httpContext)
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

Hope the above helps!

**Comment by vova3211** [comment]
HI @sayron5, since version 6.7.0 `Id` property use native mongodb type ObjectId. You need to migrate your db or use lower versions.

See related issues #41 #44

**Comment by sayron5** [comment]
Ok, thanks!
