### ISSUE TITLE
MongoUser and MongoRole saved in separate database

### ISSUE THREAD

**Issue by hakeemoriola** [matteofabbri/AspNetCore.Identity.Mongo#50]
Why is ApplicationUser and ApplicationRole collections saved in 'default' database other than the conected database?

**Comment by vova3211** [comment]
Hi @hakeemoriola!
If you don't specify database name in connection string - by default using `default` db.
Can you share your connection string?

**Comment by matteofabbri** [comment]
@hakeemoriola if you look here you will see that database name is part of the connection string

mongodb://<SERVER ADDRESS>/<DATABASE NAME>
