### ISSUE TITLE
FormatException when retrieving user by claims using UserManager

### ISSUE THREAD

**Issue by dboschm** [matteofabbri/AspNetCore.Identity.Mongo#51]
Hi,
I'm getting an error retrieving the actual user Object inside controller method. 
The code line retrieving the User is the following:
`var user = await userManager.GetUserAsync(HttpContext.User)` 

My Application User derives from MongoUser:
`public class ApplicationUser: MongoUser { ... }`

The registration of Mongo Identity looks like this:
```
 services.AddIdentityMongoDbProvider<User, MongoRole>(
        opt => {
          opt.Password.RequiredLength = int.Parse(configuration["Password:RequiredLength"]);
          opt.Password.RequiredUniqueChars = int.Parse(configuration["Password:RequiredUniqueChars"]);
          opt.Password.RequireNonAlphanumeric = bool.Parse(configuration["Password:RequireNonAlphanumeric"]);
          opt.Password.RequireLowercase = bool.Parse(configuration["Password:RequireLowercase"]);
          opt.Password.RequireUppercase = bool.Parse(configuration["Password:RequireUppercase"]);
          opt.Password.RequireDigit = bool.Parse(configuration["Password:RequireDigit"]);

          opt.User.RequireUniqueEmail = true;
          opt.SignIn.RequireConfirmedEmail = true;
        },
      mongoOpts =>
      {
        mongoOpts.ConnectionString = configuration["MongoDb:ConnectionString"];
      }).AddDefaultTokenProviders();
```
The occuring error looks like this: 
```
 An unhandled exception has occurred while executing the request.
System.FormatException: 'some.email.of.a.user.that.exists.in.db@example.com' is not a valid 24 digit hex string.
   at MongoDB.Bson.ObjectId.Parse(String s)
   at AspNetCore.Identity.Mongo.Stores.UserStore`2.FindByIdAsync(String userId, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Identity.UserManager`1.FindByIdAsync(String userId)
   at Microsoft.AspNetCore.Identity.UserManager`1.GetUserAsync(ClaimsPrincipal principal)
   at ###SOMENAMESPACE###.##SomeController.SomeAction()
```
Seems that MongoIdentity is trying to parse the email claim of the signed in User as ObjectId, instead of taking the objectId claim (there is indeed one). Any suggestions how to fix that. Maybe some claims settings...

**Comment by vova3211** [comment]
HI @dboschm!
As i can see from error message you have `_id` prop in db like email? Since version 6.7.0 library using native ObjectId mongodb type for `Id` property.

Possible duplicate #44 #49. Please check it.

**Comment by vova3211** [comment]
@matteofabbri We already have 3 or 4 issues with migration problem.I am going to create some migration guide to version 6.7.0. What you think about it?

**Comment by dboschm** [comment]
@vova3211 I fixed the problem. It was an issue in the configuration of my jwt-claims. It seems that `JwtRegisteredClaimNames.Sub` claim corresponds to a `NameIdentifier` claim which is used by the UserManager to retrieve the User object. So I had two `NameIdentifier` claims the first one contained the email and the second one the actual ObjectId string. From my perspective, this issue can be closed, since it was not a MongoIdentity fault as it seemed to be.
