### ISSUE TITLE
Why two MongoUtil class with duplicate content ?!

### ISSUE THREAD

**Issue by mjebrahimi** [matteofabbri/AspNetCore.Identity.Mongo#54]
Why are there two [MongoUtil.cs](https://github.com/matteofabbri/AspNetCore.Identity.Mongo/blob/master/AspNetCore.Identity.Mongo/Mongo/MongoUtil.cs) , [MongoUtil.cs](https://github.com/matteofabbri/AspNetCore.Identity.Mongo/blob/master/AspNetCore.Identity.Mongo/MongoUtil.cs) classes with duplicate content?

**Comment by matteofabbri** [comment]
Right, fixed. Thanks
