### ISSUE TITLE
After updating my package getting this exception

### ISSUE THREAD

**Issue by zikalol** [matteofabbri/AspNetCore.Identity.Mongo#58]
Exception : 
![image](https://user-images.githubusercontent.com/52603066/83703326-21c8a180-a607-11ea-9f5f-d4669ec33871.png)
my request :
![image](https://user-images.githubusercontent.com/52603066/83703352-3442db00-a607-11ea-9da2-ed9e6aebc863.png)
Any help please ? or its a bug

**Comment by zikalol** [comment]
it seems caused by mongoDB driver

**Comment by Steinfeld91** [comment]
on RoleId assignment it's saying the result of the Select is IEnumerable, not List. I think you just need to add .ToList() before the .FirstOrDefault()

**Comment by zikalol** [comment]
> on RoleId assignment it's saying the result of the Select is IEnumerable, not List. I think you just need to add .ToList() before the .FirstOrDefault()
Same issue, it used to work in 6.7.0

**Comment by Steinfeld91** [comment]
what is x's type?

**Comment by Steinfeld91** [comment]
i might have gotten where .ToList() goes wrong. Might be:
x.RolesClaims.ToList().Where( yada yada yada
RolesClaims I think is the collection causing the problem from how the exception reads

**Comment by zikalol** [comment]
![image](https://user-images.githubusercontent.com/52603066/83708415-234c9680-a614-11ea-8367-5b12050a2243.png)
added .tolist() after the where() , it worked thank you. But didnt have this issue on 6.7.0. appreciated
