### ISSUE TITLE
No way to do custom async operations on user store

### ISSUE THREAD

**Issue by Uterr** [matteofabbri/AspNetCore.Identity.Mongo#60]
Hello! I am using AspNetCore.Identity.Mongo. I extended MongoUser class to add custom field to it (not a claim).

Now i need to make search by that field. I found solution: 

`public static async Task<MongoUserExtended> FindByUid(this UserManager<MongoUserExtended> um, string uid) {
    return um?.Users?.FirstOrDefault(x => x.Uid == uid);
}`
But whis code is syncronous, and i need asyncronous search.

I tried to cast Users as IMongoQueryable<MongoUserExtended>, but whis cast is not possible in runtime.

Is there a way to access _userCollection or make async searches in users collection? Thank you.

**Comment by vova3211** [comment]
Hi @Uterr !

To be honest your question was wonder me :) Let's explain what i've found.

So, i go deeply in the aspnetcore sources and found similar issue and related pull request:
https://github.com/dotnet/aspnetcore/issues/6331
https://github.com/dotnet/aspnetcore/pull/15248#issuecomment-545289306

In the referenced comment said that `IQueryable` can be used async. Then i investigated how to use it as async and found extension [QueryableExtensions.ToListAsync](https://docs.microsoft.com/en-us/dotnet/api/system.data.entity.queryableextensions.tolistasync?view=entity-framework-6.2.0) for entity framework.

Then i  found similar extension in mongoDB:
in `MongoDB.Driver.Core` class with extensions `IAsyncCursorSourceExtensions` which contain the same extension `ToListAsync`.

Finally, you can use `UserManager.Users` in async way like this:
```
public static Task<MongoUserExtended> FindByUid(this UserManager<MongoUserExtended> um, string uid) 
{ 
    return (um.Users as IMongoQueryable<MongoUserExtended>).FirstOrDefaultAsync(x => x.Uid == uid); 
}
```

**Comment by vova3211** [comment]
i've noticed that you tried cast IMongoQueryable. Can you provide exception what you got? 
i tested it and this solution works fine.

**Comment by Uterr** [comment]
@vova3211 thank you for your reply. 
Yes, i researched source code for user manager and mongo user sore:
https://github.com/matteofabbri/AspNetCore.Identity.Mongo/blob/master/AspNetCore.Identity.Mongo/Stores/UserStore.cs
https://github.com/aspnet/Identity/blob/master/src/Core/UserManager.cs
and i was sure it should work this way:
`	public static async Task<MongoUserExtended> FindByUid(this UserManager<MongoUserExtended> um, string uid) {
	return await ((IMongoQueryable<MongoUserExtended>)um?.Users).FirstOrDefaultAsync(x => x.Uid == uid);
}`
but when i run this code i get error:
`System.InvalidCastException: 'Unable to cast object of type 'System.Linq.EnumerableQuery`1[IdentityService.EventFlow.Commands.MongoUserExtended]' to type 'MongoDB.Driver.Linq.IMongoQueryable`1[IdentityService.EventFlow.Commands.MongoUserExtended]'.'`
In fact i have tried one more approach:
`public static async Task<MongoUserExtended> FindByUid(this UserManager<MongoUserExtended> um, string uid) {
	return await um?.Users?.FirstOrDefaultAsync(x => x.Uid == uid);
}`
using FirstOrDefaultAsync extension method from EntityFrameworkQueryableExtensions, which did not work either: 
`System.InvalidOperationException: 'The provider for the source IQueryable doesn't implement IAsyncQueryProvider. Only providers that implement IAsyncQueryProvider can be used for Entity Framework asynchronous operations.'`
apparently user store do no support IAsyncQueryProvider.

**Comment by vova3211** [comment]
I've tested it in different ways and result is the same. There are no problem to cast it directly or through extension
```
        public static Task<TestSiteUser> FindByUid(this UserManager<TestSiteUser> um, string uid)
        {
            return (um.Users as IMongoQueryable<TestSiteUser>).FirstOrDefaultAsync(x => x.Uid == uid);
        }

        public static Task<TestSiteUser> FindByUidAsync(this UserManager<TestSiteUser> um, string uid)
        {
            return ((IMongoQueryable<TestSiteUser>)um.Users).FirstOrDefaultAsync(x => x.Uid == uid);
        }
```
All of tests fine (t1-t4)
```
            var tUsers = (IMongoQueryable<TestSiteUser>)_userManager?.Users;
            var t1 = await (_userManager?.Users as IMongoQueryable<TestSiteUser>).FirstOrDefaultAsync(x => x.Uid == "test");
            var t2 = await tUsers.FirstOrDefaultAsync(x => x.Uid == "test");
            var t3 = await _userManager.FindByUid("test");
            var t4 = await _userManager.FindByUidAsync("test");
```

As i can see problem in `um?.Users`. Exception says that `um?.Users` has type `System.Linq.EnumerableQuery1[IdentityService.EventFlow.Commands.MongoUserExtended]`, but this shoud be `IQueryable<IdentityService.EventFlow.Commands.MongoUserExtended>`.

From debug:
```
var typeOriginal = _userManager.Users.GetType().ToString();
var typeAfterCast = (_userManager.Users as IMongoQueryable<TestSiteUser>).GetType().ToString();
```
Both results has type `MongoDB.Driver.Linq.MongoQueryableImpl`2[SampleSite.Identity.TestSiteUser,SampleSite.Identity.TestSiteUser]`

@Uterr can you check type of your userManager.Users? Also will be good if you'll provide more info about UserManager - did you inherited from `Microsoft.AspNetCore.IdentityUserManager<TUser>`, how you resolve it etc.

**Comment by vova3211** [comment]
Also problem can be in `IUserStore<TUser>` implementation. Would be good to saw it too if you use own store.
Any other additional info would be a plus.

**Comment by Uterr** [comment]
@vova3211 thank you for helping. 
I just realized, that we are using AspNetCore.Identity.Mongo version 3.1.5, and we should try first to update AspNetCore.Identity.Mongo to actual version. 

As of UserManager, we don't use custom user manager, and simply adding mongodb support by calling 
`services.AddIdentityMongoDbProvider<MongoUserExtended, MongoRole>(...)` so it should be default implementation. I think this problem may resolve after updating AspNetCore.Identity.Mongo in our project, and i will report about it later.

**Comment by Uterr** [comment]
@vova3211 i'we found why i cannot make this operation asynchronous in 3.1.5.
In 3.1.5 User property looks like this:
`public IQueryable<TUser> Users => _userCollection.GetAllAsync().Result.AsQueryable();`

and in 6.x:
`public IQueryable<TUser> Users => _userCollection.AsQueryable();`

And 3.1.5 code would not allow async operations, as it is evaluating users collection beforehand. And we need to update to 6.x version to fix this issue.

**Comment by vova3211** [comment]
For version 3.1.5 is not possible to do async operations on user store due to specific realization of `public IQueryable<TUser> Users`.
