### ISSUE TITLE
Migration 3.1.5 -> 5 -> 6

### ISSUE THREAD

**Issue by Uterr** [matteofabbri/AspNetCore.Identity.Mongo#61]
Hello!

To fix out previous issue: https://github.com/matteofabbri/AspNetCore.Identity.Mongo/issues/60 we need to update AspNetCore.Identity.Mongo to version 6+

There is instruction, how to migrate 5 -> 6, but there is no instruction how to migrate from 3.1.5 -> 5/6. 
I'we fount out that collection structure changed severely:
Fields names changed, structure of collection of claims of user changed also, fields type changed:
Collection Users:
_id was ObjectId in 3.1.5, became string in 5.x (and back to ObjectId in 6.x)
LocautEndDateUtc changed to LocautEnd in 5.x
ClaimStructure changed from {"Subject", "OriginalIssuer", "Issuer", "Type", "Value" } to {"_id", "UserId", "ClaimType", "ClaimValue"} in 5.x

Is there a good way to migrate from 3.1.5 to 5.x ? Have we determined changes correctly, or more has changed? Thank you.

**Comment by vova3211** [comment]
The best solution is to use the newest version.
As i can see we have different changes from version to version.

Also there was big changes with roles. Previously they stored in User entity like string (name). Now it's string too, but with id inside. Maybe some other (most likely).

I'll check all changes between 3.1.5 and 6.7.0 versions and create separate migration guide.

**Comment by vova3211** [comment]
@Uterr I already created pull request for migration guide from version 3.1.5

But you can use it right now at [migration_doc_to_newer_version branch](https://github.com/matteofabbri/AspNetCore.Identity.Mongo/blob/migration_doc_to_newer_version/docs/MigrationGuideFromVersion3_1_5ToVersion6_7_0AndUpper.md)
