### ISSUE TITLE
userManager.AddToRoleAsync succeeded but role did not persist

### ISSUE THREAD

**Issue by PetkevichP** [matteofabbri/AspNetCore.Identity.Mongo#64]
I used userManager.AddToRoleAsync (user,roleName) and the identityResult is Succeeded but the specified role did not persist.

Version info:
.net core 3.1
AspNetCore.Identity.Mongo 6.7.1

**Comment by vova3211** [comment]
Hi @PetkevichP!
Will test it today.

**Comment by vova3211** [comment]
@PetkevichP Everything working ok.
There is only 1 reason why it's "not working" - the role does not exist. If role not found in RoleStore by roleName then nothing happens.

Check that role exists.

**Comment by PetkevichP** [comment]
Yes , You are right, thanks!
