### ISSUE TITLE
mongouser no implizit conversion to identyuser

### ISSUE THREAD

**Issue by christopherpross** [matteofabbri/AspNetCore.Identity.Mongo#66]
Hey,
this is maybe a stupid question, but it is possible to provide a conversion from mongouser to identityuser? Because I have to create a dbcontext for an other library and I can only do that with the user class. IdentyDbcontext accepts only some class which implements tuser and so on.
Or do you have an idea how I could provide a dbcontext to the library?

all the best.

**Comment by vova3211** [comment]
Hi @christopherpross!
`MongoUser` inherited from `Microsoft.AspNetCore.Identity.IdentityUser<TKey>`, so yes you can cast it.

Can you explaine a little bit more about what you trying to do?

**Comment by christopherpross** [comment]
Ok, some code, hopefuly it is more clear with that. :-)

With this code, i get the following error:

Error CS0311 The type "Website.Models.ApplicationUser" cannot be used as a type parameter "TUser" in the generic type or in the generic method "IdentityDbContext <TUser>". There is no implicit reference conversion from "Website.Models.ApplicationUser" to "Microsoft.AspNetCore.Identity.IdentityUser".

```
// my user class
public class ApplicationUser : MongoUser
{
}

// my databasedbcontext:
    public class ApplicationDbContext : IdentityDbContext<ApplicationUser>
    {
        public ApplicationDbContext(DbContextOptions options)
    : base(options) { }

        protected override void OnModelCreating(ModelBuilder builder)
        {
            base.OnModelCreating(builder);

            // Customize the ASP.NET Identity model and override the defaults if needed.
            // For example, you can rename the ASP.NET Identity table names and more.
            // Add your customizations after calling base.OnModelCreating(builder);
        }
    
// for example I need here the dbcontext:
            services.AddDbContext<ApplicationDbContext>(options =>
            {
                //options.UseSqlServer(Configuration.GetConnectionString("DefaultConnection"));
                options.UseOpenIddict();
            });

// or here
// Register the OpenIddict core components.
                .AddCore(options =>
                {
                    // Configure OpenIddict to use the Entity Framework Core stores and models.
                    // Note: call ReplaceDefaultEntities() to replace the default OpenIddict entities.
                    options.UseEntityFrameworkCore()
                           .UseDbContext<ApplicationDbContext>();
                })

                

```


Maybe this helps to understand my problem?

**Comment by vova3211** [comment]
As i mentioned above `MongoUser` inherited from `Microsoft.AspNetCore.Identity.IdentityUser<TKey>`  where TKey is ObjectId.
`Microsoft.AspNetCore.Identity.IdentityUser` is inherited to from `Microsoft.AspNetCore.Identity.IdentityUser<TKey>` where TKey is string.
They both have the same parent, but `IdentityDbContext` requires specific realization of `Microsoft.AspNetCore.Identity.IdentityUser<TKey>`

So, it's not possible to use `MongoUser` directly in `IdentityDbContext`.

**Comment by vova3211** [comment]
Closed as no response for long time. If you'll have any questions, re-open it.
