### ISSUE TITLE
Migrate from 5.1.0.15 to 6.x

### ISSUE THREAD

**Issue by eliwinkelman** [matteofabbri/AspNetCore.Identity.Mongo#67]
I am migrating a project from AspNetCore.Identity.Mongo 5.1.0.15 to 6.x and IIdentityUserCollection has been removed in 6.x. What should I use instead?

**Comment by vova3211** [comment]
You should use `UserManager<TUser>` and `RoleManager<TRole>` instead.
Library provide mongodb implementation for all necessary things inside `UserManager<TUser>` and `RoleManager<TRole>`, like a `UserStore`, `RoleStore` etc. So you don't need to use it explicitly by injecting stuff from lib.
