### ISSUE TITLE
Email '' is invalid.

### ISSUE THREAD

**Issue by tugkan84** [matteofabbri/AspNetCore.Identity.Mongo#7]
Hello 
`var user = new ApplicationUser { UserName = Input.Email, Email = Input.Email };`
`var result = await _userManager.CreateAsync(user, Input.Password);`
  always return "Email '' is invalid." error. 
if i use `opt.User.RequireUniqueEmail = false;` its passes but i want to use unique emails.
What i am missing to do?

Thanks

**Comment by 7Kronos** [comment]
@tugkan84 Strange it works well for me. Have you checked the email format ?

**Comment by tugkan84** [comment]
hi @7Kronos. mail is deneme@tmail.com

**Comment by matteofabbri** [comment]
That's weird. And by the way the store does not perform any check on the validity of the mail,
Have you checked inside Mongo if the mail is stored correctly ?

**Comment by matteofabbri** [comment]
ps: i just tested your email on my website (which obviously runs on my identity system) and runs smooth as silk.
I hope you don't mind, i will delete the fake user asap (maybe the time to fix the issue)
![immagine](https://user-images.githubusercontent.com/130935/48223843-70b14500-e398-11e8-85db-1db2995b1fec.png)

**Comment by tugkan84** [comment]
@matteofabbri yes i checked from mongo and also i set NormalizeEmail too.
Username works perfect but Email not.I think only i face that problem so I will manualy control email before createAsync. By the way i can close the issue. 

Thank you very much of your responses.

**Comment by matteofabbri** [comment]
what you mean for "_also i set NormalizeEmail too."_ ?

**Comment by tugkan84** [comment]
I want to say I try to set NormalizedEmail field too while working on.

**Comment by matteofabbri** [comment]
Fixed in today package
