### ISSUE TITLE
Using of different Id type

### ISSUE THREAD

**Issue by greyhord** [matteofabbri/AspNetCore.Identity.Mongo#71]
Hi,

Is it possible to override ObjectId usage with Guid as a key?

**Comment by Daviidbit** [comment]
It would be a great help !!

**Comment by vova3211** [comment]
At the moment it's not possible.
`AspNetCore.Identity.Mongo.Model.MongoUser` inherited from `Microsoft.AspNetCore.Identity.IdentityUser<TKey>` where `<TKey>` is `MongoDB.Bson.ObjectId`.

Basically, it's possible to do what you want. There should be something like `AspNetCore.Identity.Mongo.Model.MongoUser<TKey>` where you can set any type.

**Comment by louislewis2** [comment]
Hi,

Has this change been released yet to nuget?

**Comment by radeanurazvan** [comment]
Any news on this?

**Comment by matteofabbri** [comment]
@radeanurazvan sorry but due to Covid related shits i dont have the time neither the energy to take care of the packet at the moment :(

**Comment by Softtinn** [comment]
We are also affected by this issue.

@matteofabbri 
Sorry to hear that - hope you are well!

**Comment by KonH** [comment]
We suffer from that issue too.
Also, for now, AddIdentityMongoDbProvider has no option to use separated keys for user and role, unfortunately.

**Comment by vova3211** [comment]
@KonH what the point to use different keys for user and role collactions? Usually used the same key for database integrity and consistency.
If you think that this should be implemented, please, create separate issue and explain what you are trying to achieve.

**Comment by Daviidbit** [comment]
Hi, In version 6.0.0 you can use simple guid as _id field. but in newer
versions the only option is ObjectId. In some cases there is a need to use
different keys such is integer on strings. if this could be implemented, it
would be a great help. I am still using version 6.0.0

**Comment by vova3211** [comment]
Hi @Daviidbit , in newer version you can set `Key` for User and Role entities.
`MongoUser` - using ObjectId as a Key, because it's "native" mongo id.

But you can specify your Key - `MongoUser<Key>`:
`MongoUser<string>` - string equivalent

And in your startup use:
```
services.AddIdentityMongoDbProvider<MongoUser<string>, MongoRole<string>, string>(identity =>
    {
        identity.Password.RequireDigit = false;
        // other params
    } ,
    mongo =>
    {
        mongo.ConnectionString = ConnectionString;
        // other params
    }
);
```

**Comment by KonH** [comment]
> @KonH what the point to use different keys for user and role collactions? Usually used the same key for database integrity and consistency.
> If you think that this should be implemented, please, create separate issue and explain what you are trying to achieve.

We use role name as a role key (for some reason), but object Id as a user key. It isn't critical for now.

**Comment by vova3211** [comment]
Hi there!

New nuget versions already published:
[.Net Core 3.x version](https://www.nuget.org/packages/AspNetCore.Identity.Mongo/6.7.3)
[.Net 5.x version](https://www.nuget.org/packages/AspNetCore.Identity.Mongo/8.0.0)
