### ISSUE TITLE
Nuget package publish

### ISSUE THREAD

**Issue by vova3211** [matteofabbri/AspNetCore.Identity.Mongo#72]
Hi @matteofabbri !! I had been a little bit busy, but now i'm back :)

I've notice that you facing issue with nuget. Can you explain a little bit more about problem? Can we somehow help you?

As i understood, you have problem with publishing nuget package because of your IP. And nuget can't validate that you are owner, am i right?

Some approaches what i see at the moment:

1. You can give access to any of collaborators and they try to publish new version.
2. Setup GitHub Actions to auto publish packages.

Second is better - you won't need to take care all time for publishing new version of package (just trigger when needed) and also publishing will going from "trusted" IPs. GitHub give 2 000 free minutes for it (more that enough for us). If it's relevant, i can investigate and setup it.

**Comment by matteofabbri** [comment]
@vova3211 hey, thanks for your help. I'm dealing with big Covid related family issues so to be honest Nuget login is the very least of my problem.
I would be very happy to add you to the control and even more to setup the automatic deploy but to do all of those i need to access my account that for the moment is locked ( i had the wonderful idea to follow instruction of help service and change security information).
When i will have time i will be very happy to take some time and fix all those shit in one pass

**Comment by vova3211** [comment]
oh, i see. Hope you're doing well!
