### ISSUE TITLE
System.NotSupportedException: 'TypeConverter cannot convert from System.String.'

### ISSUE THREAD

**Issue by Matman94** [matteofabbri/AspNetCore.Identity.Mongo#74]
Hi,
There is some problem when I give the role to the user by /User/AddToRole(string roleName, string userName). ConvertIdFromString function catch the fallowing error:

![image](https://user-images.githubusercontent.com/23061794/92301116-17e57000-ef61-11ea-82d6-a6e50e593e7f.png)

Is this bug or I doing something wrong ?

**Comment by jiataocai** [comment]
I fixed it by:
**Added a new convert class:**
public class ObjectIdConverter : TypeConverter
    {
        public override bool CanConvertFrom(ITypeDescriptorContext context,
                                            Type sourceType)
        {
            if (sourceType == typeof(string))
                return true;
            return base.CanConvertFrom(context, sourceType);
        }

        public override object ConvertFrom(ITypeDescriptorContext context,
                                           System.Globalization.CultureInfo culture,
                                           object value)
        {
            if (value is string)
                return MongoDB.Bson.ObjectId.Parse((string)value);
            return base.ConvertFrom(context, culture, value);
        }

        public override bool CanConvertTo(ITypeDescriptorContext context,
                                          Type destinationType)
        {
            if (destinationType == typeof(string))
                return true;
            return base.CanConvertTo(context, destinationType);
        }

        public override object ConvertTo(ITypeDescriptorContext context,
                                         System.Globalization.CultureInfo culture,
                                         object value,
                                         Type destinationType)
        {
            if (destinationType == typeof(string))
                return ((MongoDB.Bson.ObjectId)value).ToString();
            return base.ConvertTo(context, culture, value, destinationType);
        }
    }

**and then modified the: ConvertIdFromString(string id) in  userStore.cs:**

public virtual TKey ConvertIdFromString(string id)
        {
            if (id == null)
            {
                return default(TKey);
            }
            if (typeof(TKey).Name == "ObjectId")
            {
                var obj = new ObjectIdConverter().ConvertFromInvariantString(id);
                return (TKey)obj;
            }
            else
            {
                return (TKey)TypeDescriptor.GetConverter(typeof(TKey)).ConvertFromInvariantString(id);
            }
        }

**Comment by vova3211** [comment]
@jiataocai thanks, i did exactly what you, but without modification of `UserStore` or `RoleStore` ;)
after Matteo merge pull request and publish new version with fix, you can upgrade package.

**Comment by Matman94** [comment]
Thanks for your help, guys.
