### ISSUE TITLE
Ability to subscribe to Mongo Events

### ISSUE THREAD

**Issue by dgrozenok** [matteofabbri/AspNetCore.Identity.Mongo#76]
To set up the MongoDB instrumentation for the OpenTelemetry tracing I need to configure the MongoClient like this:
https://github.com/jbogard/MongoDB.Driver.Core.Extensions.DiagnosticSources

```
var clientSettings = MongoClientSettings.FromUrl(new MongoUrl("mongodb://localhost"));
clientSettings.ClusterConfigurator = cb => cb.Subscribe(new DiagnosticsActivityEventSubscriber());
var mongoClient = new MongoClient(clientSettings);
```

Is it possible to provide such ability to intercept the MongoClient creation during the setup?

**Comment by vova3211** [comment]
What I can said on that:

We need to add ability to setup callback action for `MongoClientSettings.ClusterConfigurator` when we are registering Identity at `services.AddIdentityMongoDbProvider(...);`
It will look smth like:
```
services.AddIdentityMongoDbProvider<MongoUser, MongoRole>(identityOptions =>
{
    identityOptions.Password.RequiredLength = 6;
}, mongoIdentityOptions => {
    mongoIdentityOptions.ConnectionString = "mongodb://localhost/myDB";
    mongoIdentityOptions.ClientClusterConfigurator = cb => cb.Subscribe(new DiagnosticsActivityEventSubscriber());
});
```

**Comment by vova3211** [comment]
@dgrozenok nuget version 6.8.0-rc published with ability to set ClusterConfigurator. You can test it and send response until it will be published as release version.

**Comment by vova3211** [comment]
Version [8.1.0](https://www.nuget.org/packages/AspNetCore.Identity.Mongo/8.1.0) for .NET 5.0 and version [6.8.0](https://www.nuget.org/packages/AspNetCore.Identity.Mongo/6.8.0) for .Net 3.1 already published.
