### ISSUE TITLE
Tutorial 

### ISSUE THREAD

**Issue by mayankjanmejay** [matteofabbri/AspNetCore.Identity.Mongo#78]
Hi Guys,

I apologie for the super newbie question. 

Is there is tutorial on how to add this to a project?

**Comment by vova3211** [comment]
Hi, is this still relevant for you?

Readme file at the root of project has [How to use section](https://github.com/matteofabbri/AspNetCore.Identity.Mongo#how-to-use)

**Comment by mayankjanmejay** [comment]
Hey, 
Thank you very much for your response.
So i created a new .net core 5.0 api. Installed your package and then inserted the config which you pointed me to and when i try to use 
api/token or api/Account/Register 

I get 404.

Please help.

**Comment by vova3211** [comment]
Library does not support .Net 5.0.

I'll open separate issue for supporting .Net 5.0, but the usage will be the same as mentioned in readme.

Also lib does not provide any API functionality such as `api/token` or any other endpoint.

It's like mongodb wrapper on ASP.NET Identity. It is more about user/role management.

**Comment by vova3211** [comment]
Hi @mayankjanmejay !

We released new package version that supports .Net 5.0. [Nuget package](https://www.nuget.org/packages/AspNetCore.Identity.Mongo/8.0.0)
Also [how-to-use section](https://github.com/matteofabbri/AspNetCore.Identity.Mongo#how-to-use) updated.
