### ISSUE TITLE
blazor tutorial with dotnet 5.0

### ISSUE THREAD

**Issue by przemo1983** [matteofabbri/AspNetCore.Identity.Mongo#85]
is it possible to provide simple blazor tutorial for dotnet 5.0?

**Comment by vova3211** [comment]
Hi,
please take a look at this issues #40 #52 . 
[Specially that comment](https://github.com/matteofabbri/AspNetCore.Identity.Mongo/issues/40#issuecomment-604649026)

It's for .Net Core 3.1, I believe, but should be also useful for .Net 5.

**Comment by przemo1983** [comment]
Thank you very much. :)
