### ISSUE TITLE
Unable to post Register using sample project

### ISSUE THREAD

**Issue by mayankjanmejay** [matteofabbri/AspNetCore.Identity.Mongo#90]
Hi,

I downloaded and configured your AspNetCore.Identity.Mongo sample project. I am able to register & login via the browser but when I try to replicate the Register request via postman. I keep getting 400, Bad request.

Please help.

Is there something I am missing from the headers?

https://github.com/matteofabbri/AspNetCore.Identity.Mongo

![image](https://user-images.githubusercontent.com/35850067/105994968-01c38200-60b1-11eb-87dc-d06d066886e1.png)
![image](https://user-images.githubusercontent.com/35850067/105995004-0d16ad80-60b1-11eb-9dbe-871cd0762dd1.png)

**Comment by vova3211** [comment]
Hi @mayankjanmejay ,
Test site is Razor-based project and it uses cookies and anti forgery tokens.

1. You need enable cookies for localhost domain (which seems to be done)
2. You need add 1 more parametr in body "__RequestVerificationToken" with anti forgery token value.
Also use x-www-form-urlencoded instead of form-data. (Should work with form-data, but x-www-form-urlencoded will work for sure)

**Comment by mayankjanmejay** [comment]
Ahh I see now. 
I disabled the antiforgery token for testing and now the endpoint works, Just one more question. 

When I initiate Account/Login I get a html webpage as the return is it possible to get the token instead which I could use to make other authenticated queries?
![image](https://user-images.githubusercontent.com/35850067/106005508-f8d8ad80-60bc-11eb-8da0-1a0c2dad6c40.png)

**Comment by vova3211** [comment]
As I undestand, you want to have an API project and use JWT token for authorization, right?

Sample is stateful app and using cookie to store information about authenticated user. It does not suitable for this.
You need to implement own API and JWT functionality instead.

Useful links:
[jwt-auth-in-asp-net-core](https://codeburst.io/jwt-auth-in-asp-net-core-148fb72bed03)
[IdentityServer4](https://github.com/IdentityServer/IdentityServer4)

**Comment by mayankjanmejay** [comment]
From what I understood from your comment. I couldn't use the sample project to make a api. So I created a new ASP .net code 5 project and followed [this tutorial ](http://alejandroruizvarela.blogspot.com/2018/11/aspnet-core-identity-with-cosmos-db.html) to integrate your plugin into the project. 

The tutorial is missing token generation so i googled and fixed that but then when I try to use the token to auth it doesnt work to send the token as a bearer header via postman. 

I have attached the project below. 

[nAPI.zip](https://github.com/matteofabbri/AspNetCore.Identity.Mongo/files/5894991/nAPI.zip)
![image](https://user-images.githubusercontent.com/35850067/106301738-be0f7a80-6260-11eb-8f1d-60a292f8613a.png)


Thank you for your help

**Comment by vova3211** [comment]
Hi, tutorial is fine. At the end of article you can find link to [github repository](https://github.com/AlejandroRuiz/CosmosDBTutorial). It has [AuthenticationHelper](https://github.com/AlejandroRuiz/CosmosDBTutorial/blob/master/MyAwesomeWebApi/Helpers/AuthenticationHelper.cs) where token generates.

Also your token generation configs should match in Startup where you register jwt validation and in `JwtManager.GenerateToken`. You are using different secret for token generation and token validation.

If you change `JwtManager.GenerateToken` implementation, it will work fine.
Example (based on [AuthenticationHelper](https://github.com/AlejandroRuiz/CosmosDBTutorial/blob/master/MyAwesomeWebApi/Helpers/AuthenticationHelper.cs)):
```
public static string GenerateToken(string username, string userId, int expireMinutes = 20)
        {
            var claims = new List<Claim>
            {
                new Claim(JwtRegisteredClaimNames.Sub, username),
                new Claim(JwtRegisteredClaimNames.Jti, Guid.NewGuid().ToString()),
                new Claim(ClaimTypes.NameIdentifier, userId)
            };

            var key = new SymmetricSecurityKey(System.Text.Encoding.UTF8.GetBytes("=^e&^f7Sv$!z*mYrsdWzVSe&Z22fLR&5"));
            var creds = new SigningCredentials(key, SecurityAlgorithms.HmacSha256);
            var expires = DateTime.Now.AddMinutes(Convert.ToDouble(expireMinutes));

            var token = new JwtSecurityToken(
                "Greensoft.ro",
                "Greensoft.ro",
                claims,
                expires: expires,
                signingCredentials: creds
            );
            return new JwtSecurityTokenHandler().WriteToken(token);
        }
```

**Comment by mayankjanmejay** [comment]
I added the changes you suggested and it is working. Thank you very much for your help.
