### ISSUE TITLE
Using AspNetCore.Identity.Mongo in an api project

### ISSUE THREAD

**Issue by Ateyib2** [matteofabbri/AspNetCore.Identity.Mongo#91]
Hello, 

There probably is a way to do this already but I was wondering what I need to do in order to this package in an API project for a backend for my mobile application. 

It could be returning a token when a user signs in instead of a View(),

Help greatly appreciated.

**Comment by Ateyib2** [comment]
Found solution

**Comment by abhigantech** [comment]
Please share the solution.
