### ISSUE TITLE
Allow to use X509 certificates to connect to Mongo

### ISSUE THREAD

**Issue by roman-ledermann-erni** [matteofabbri/AspNetCore.Identity.Mongo#92]
MongoDB.Driver does not support the usage of TLS parameters related to X509 certificates in the connection string. You need to call a different constructor of the MongoClient class to be able to use certificates to authenticate against a database. Right now the extension methods available in AspNetCore.Identity.Mongo only allow to use a connection string.

The solution would be to add a new extension method that allows to set the certificate file that should be used for authentication.

An alternative solution could be to add a new extension method for every authentication mechanism (SCRAM, X509, GSSAPI, LDAP).

**Comment by vova3211** [comment]
Hi @roman-ledermann-erni ! Thanks for request.

The best solution is add extension which receive `MongoDB.Driver.MongoClientSettings`. Then you can set any option you want/require. Like ssl/tls, certificates, timeouts etc.

**Comment by vova3211** [comment]
Also what version of .Net Core you required?
.Net 5.0 now is the main framework where this feature will be added. Do you need it in .Net Core 3.x or else?

**Comment by roman-ledermann-erni** [comment]
Hi @vova3211

I would need the change for .NET Core 3.1 since we do not have plans yet to update to .NET 5 anytime soon

**Comment by vova3211** [comment]
@roman-ledermann-erni nuget version 6.8.0-rc published with ability to set SslSettings. You can test it and send response until it will be published as release version.

**Comment by roman-ledermann-erni** [comment]
Finally had time to test your changes. Everything works as expected

**Comment by vova3211** [comment]
Version [8.1.0](https://www.nuget.org/packages/AspNetCore.Identity.Mongo/8.1.0) for .NET 5.0 and version [6.8.0](https://www.nuget.org/packages/AspNetCore.Identity.Mongo/6.8.0) for .Net 3.1 already published.
