### ISSUE TITLE
Performance issue

### ISSUE THREAD

**Issue by thebestgin** [matteofabbri/AspNetCore.Identity.Mongo#93]
Nice project.

You made sure to index the right properties (NormalizedEmail and NormalizedUserName) in MongoDB. Queries are very fast because of this.

I noticed that the library is very slow if I register users by: 
`_signInManager.UserManager.CreateAsync(user, autoPassword);`

With my configuration I reach a maximum of 40 registrations per second. If I use a SQL server I reach 80 registrations per seconds. Same system.

If I insert the users directly into another collection of mongoDB,  I reach several hundred inserts per second. 

Is this normal?

**Comment by vova3211** [comment]
Hi @thebestgin ,

Comparison between direct insertion and though framework does not make sense. Direct queries always faster then via any wrappers.

But you are definitely right that `CreateAsync` method a little bit slow. There are few updates after insert - if `user.Email` not empty, will be 2 more updates around normalization of email. Which not make sense, because all necessary transformations should be done before insertion.

**Comment by vova3211** [comment]
Could be more of this kind of problem in other methods. Need to check them all.

**Comment by thebestgin** [comment]
Thank you for your quick reply. 
I'll take a look at your code as well.

If I can test anything, let me know.
Really cool project.

**Comment by vova3211** [comment]
There is misconception in implementation of UserStore/RoleStore. It making some changes which not suppose to do. It is doing the same what `UserManager` do, and as a consequence we have multiple operations (same operations or unnecessary) on the 1 object.

**Comment by thebestgin** [comment]
> @thebestgin Would be great if you'll provide list of tools you used to test. Some code snippets/repository would be useful also.

I will prepare a full Asp project for you this weekend.

**Comment by thebestgin** [comment]
I have implemented a small test program.
This library AspNetCore.Identity.Mongo manages 40 registrations per second with my PC configuration.

I tested a few other MongoDB identity libraries. All of them reach about 40 registrations per second.
Maybe we can get a little more out of it.

I'm still finishing the test project and will make it available

**Comment by thebestgin** [comment]
[IndentityAndMongoDBTesting.zip](https://github.com/matteofabbri/AspNetCore.Identity.Mongo/files/6252434/IndentityAndMongoDBTesting.zip)
This is my test project. It is very basic.

**Comment by bugproof** [comment]
@thebestgin How do you test how many registrations per second can you make?

**Comment by thebestgin** [comment]
I test with the call of an Async method in a For Loop. I measure the total time until all Async methods are finished. Then I calculate the average value for registrations per second.

It is a very simple way to evaluate the performance. The whole thing can also be parallelized. For me, it is enough to compare technologies with each other.

**Comment by thebestgin** [comment]
> @thebestgin How do you test how many registrations per second can you make?

I test with the call of an Async method in a For Loop. I measure the total time until all Async methods are finished. Then I calculate the average value for registrations per second.

It is a very simple way to evaluate the performance. The whole thing can also be parallelized. For me, it is enough to compare technologies with each other.

**Comment by vova3211** [comment]
There is test package [8.2.0-alpha](https://www.nuget.org/packages/AspNetCore.Identity.Mongo/8.2.0-alpha) with performance improvements.

**Comment by thebestgin** [comment]
> There is test package [8.2.0-alpha](https://www.nuget.org/packages/AspNetCore.Identity.Mongo/8.2.0-alpha) with performance improvements.

Good job, you have doubled the performance with my PC configuration.

**Comment by vova3211** [comment]
New package release [8.2.0](https://www.nuget.org/packages/AspNetCore.Identity.Mongo/8.2.0) includes that functionality.
