### ISSUE TITLE
Blazor webassembly compatible?

### ISSUE THREAD

**Issue by matteoventuri7** [matteofabbri/AspNetCore.Identity.Mongo#97]
Is it compatible with Blazor Webassembly?

**Comment by matteoventuri7** [comment]
Attach error: "Non è possibile usare il tipo 'Server.Models.ApplicationUser' come parametro di tipo 'TUser' nel metodo o nel tipo generico 'ApiAuthorizationDbContext<TUser>'. Non esistono conversioni implicite di riferimenti da 'Server.Models.ApplicationUser' a 'Microsoft.AspNetCore.Identity.IdentityUser'.	Server	C:\Users\mvent\Desktop\blazormongologin\blazormongologin\Server\Data\ApplicationDbContext.cs	14	N/D
"
ApplicationUser derives from MongoUser<string>

**Comment by vova3211** [comment]
Hi @matteoventuri7 ,
re 1: yes it is compatible with Blazor.

re 2:
Please use english or translate error before sharing.

Your error message translated with google:
> It is not possible to use the type 'Server.Models.ApplicationUser' as a parameter of the type 'TUser' in the method or in the generic type 'ApiAuthorizationDbContext'. There are no implicit conversations for references to 'Server.Models.ApplicationUser' to 'Microsoft.AspNetCore.Identity.IdentityUser'

Can you provide more info what is `ApiAuthorizationDbContext` an how you use it?

**Comment by matteoventuri7** [comment]
I created new Blazor Webassembly project with hosted .net backend. Backend side, ApplicationDbContext inherits from ApiAuthorizationDbContext<ApplicationUser> where ApplicationUser is MongoUser<string> and error appears.
Youi can replicate creating new blazor webassembly project on Visual studio 2019 with .NET 5

**Comment by vova3211** [comment]
please look at comment
https://github.com/matteofabbri/AspNetCore.Identity.Mongo/issues/85#issuecomment-765308579

**Comment by matteoventuri7** [comment]
Perfect! I suggest to link it in readme.

**Comment by matteoventuri7** [comment]
This example is for Blazor Server, i mean Blazro Webassembly with host .net.

**Comment by vova3211** [comment]
I am not familiar with Blazor Webassembly, but usage will be the same as for Blazor Server.
Your previous message with error says that you have problem with `ApiAuthorizationDbContext` which is not a part of this library, so I assume problem not in it.

If `ApiAuthorizationDbContext` is [apiauthorizationdbcontext](https://docs.microsoft.com/ru-ru/dotnet/api/microsoft.aspnetcore.apiauthorization.identityserver.apiauthorizationdbcontext-1?view=aspnetcore-5.0) then you doing something wrong, because it for SQL-like databases. This library use MongoDB.

Also that thread can be useful https://github.com/dotnet/aspnetcore/issues/9548

**Comment by vova3211** [comment]
What more - this library only about ASP.NET Core Identity framework and have nothing related to IdentityServer.

**Comment by matteoventuri7** [comment]
Blazor Server and Blazor Webassembly are different: Blazor server uses SignalR, Blazor Webassembly uses webassembly and call REST API backend.
This is a extract from ApiAuthorizationDbContext doc page: "Database abstraction for a combined DbContext using ASP.NET Identity and Identity Server." Nowhere is it written that "it for SQL-like databases" like you said.

This is my code:
class ApplicationDbContext : ApiAuthorizationDbContext< ApplicationUser >
class ApplicationUser : MongoUser< string >
ApiAuthorizationDbContext wants ApplicationUser inherits from IdentityUser but MongoUser inherits from IdentityUser<TKey>: i think error is here.

**Comment by vova3211** [comment]
Docs should not say it directly, but it is.

Did you check thread what i sent? `ApiAuthorizationDbContext` is using for default scenario. If you need `IdentityUser<TKey>` with different `TKey`, you should implement your own context inherited from `DbContext`.
But as I said it won't work with mongodb.

Would be useful if you'll describe what you trying to achieve, share code snippets / test repository (specially with part how you resolve services) etc.

**Comment by matteoventuri7** [comment]
Here the project with error: https://github.com/matteoventuri7/blazormongologin
Download and compile.

**Comment by vova3211** [comment]
The problem in the part of registration IdentityServer4.
```
services.AddIdentityServer()
                .AddApiAuthorization<ApplicationUser, ApplicationDbContext>();
```

You should register your own implementation of base services/interfaces to work with mongodb (instead of using default). Here is example from IdentityServer4 docs [IdentityServer4.Samples.Mongo](https://github.com/souzartn/IdentityServer4.Samples.Mongo)

**Comment by matteoventuri7** [comment]
Ok, the response is "in this moment AspNetCore.Identity.Mongo is not compatible with Blazor Wasm".
Do you think will be some implementation about this?

**Comment by vova3211** [comment]
I would not say that "AspNetCore.Identity.Mongo is not compatible with Blazor Wasm".
You have problems with using `MongoUser` from this lib in the `Microsoft.AspNetCore.ApiAuthorization.IdentityServer.ApiAuthorizationDbContext`. All info in my comments above.

You can ask help in [aspnetcore](https://github.com/dotnet/aspnetcore) community. There is nothing I can do more for you.

**Comment by artyom-p** [comment]
Same issue here :(

**Comment by vova3211** [comment]
If someone provide working example of Blazor WebAssembly + IS4 + SQL, I'll try to setup it with MongoDB.

**Comment by artyom-p** [comment]
Its the default blazor webassembly template which is not working with mongo.
Just add Hosted option when creating a template, and use Individual user accounts.
![image](https://user-images.githubusercontent.com/3993463/124763016-2f540780-df3c-11eb-906e-d2b49127df8b.png)

**Comment by vova3211** [comment]
Hey, I created sample project [BWA-IS4-MongoDB](https://github.com/vova3211/BWA-IS4-MongoDB).
I used default blazor webassembly template, some notes around implementation:
1. `AddIdentityMongoDbProvider<MongoUser>` inside uses `AddIdentity<TUser, TRole>()` that registers extra Authentication options, which conflict with `AddIdentityServerJwt()`. So to be able use it, you should register only MongodbStores:
```
services
      .AddDefaultIdentity<ApplicationUser>(identity =>
      {
          identity.SignIn.RequireConfirmedAccount = true;
          // other options
      })
      .AddMongoDbStores<ApplicationUser>(
          mongo =>
          {
              mongo.ConnectionString = Configuration["MongoDB:MongoConnection"];
              // other options
          })
      .AddDefaultTokenProviders();
```
2. Some services are internal in original aspnet core repository, so they just copied ([folder](https://github.com/vova3211/BWA-IS4-MongoDB/tree/main/WebApplication1/Server/IdentityServer/Microsoft)). [Resolved here](https://github.com/vova3211/BWA-IS4-MongoDB/blob/e51f4d8bff37895d0dceadbf2b7e5469b0f971c1/WebApplication1/Server/IdentityServer/IdentityServerBuilderExtensions.cs#L42)

Hope it will help.

**Comment by artyom-p** [comment]
Did a quick test, seems like it works, thank you!

**Comment by vova3211** [comment]
Closed as no response for long time. If you'll have any questions, re-open it.
