### ISSUE TITLE
Support for AddIdentityCore

### ISSUE THREAD

**Issue by iamtheluckyest** [matteofabbri/AspNetCore.Identity.Mongo#99]
**Is your feature request related to a problem? Please describe.**
As currently implemented, `AddIdentityMongoDbProvider` uses `services.AddIdentity`. When a user is unauthenticated, rather than sending a 401, Identity tries to redirect to login. In the web API project I'm working on, this attempt to redirect results in a 404. This means that the consequence of attempting a route the user is unauthorized for is a 404 when it should be a 401.

You can see the log info here.
```

Microsoft.AspNetCore.Authorization.DefaultAuthorizationService[2]
      Authorization failed. These requirements were not met:
      DenyAnonymousAuthorizationRequirement: Requires an authenticated user.
info: Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker[3]
      Authorization failed for the request at filter 'Microsoft.AspNetCore.Mvc.Authorization.AuthorizeFilter'.
info: Microsoft.AspNetCore.Mvc.ChallengeResult[1]
      Executing ChallengeResult with authentication schemes ().
info: Microsoft.AspNetCore.Authentication.Cookies.CookieAuthenticationHandler[12]
      AuthenticationScheme: Identity.Application was challenged.
info: Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker[2]
      Executed action ActivitiesApi.Controllers.ActivitiesController.Get (API) in 29.4264ms
info: Microsoft.AspNetCore.Routing.EndpointMiddleware[1]
      Executed endpoint 'ActivitiesApi.Controllers.ActivitiesController.Get (API)'
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished HTTP/1.1 GET http://localhost:5000/api/activities/60c7b914cc485fb584a7e139 - - - 302 0 - 161.6426ms
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/1.1 GET http://localhost:5000/Account/Login?ReturnUrl=%2Fapi%2Factivities%2F60c7b914cc485fb584a7e139 - -
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished HTTP/1.1 GET http://localhost:5000/Account/Login?ReturnUrl=%2Fapi%2Factivities%2F60c7b914cc485fb584a7e139 - - - 404 0 - 9.1568ms
```

**Describe the solution you'd like**
This problem can be solved by using `services.AddIdentityCore` instead of `services.AddIdentity`. Ideally, another method, perhaps `AddIdentityCoreMongoDbProvider`, could be written that implements AddIdentityCore rather than AddIdentity.

**Describe alternatives you've considered**
Not sure what else I can do to get around this.

**Additional context**
This [issue](https://github.com/openiddict/openiddict-core/issues/337) has more information that I believe is related to this problem of redirecting rather than sending a 401.

**Comment by vova3211** [comment]
Hi @iamtheluckyest ! Please provider an extra info:

1. version of nuget package you are using.
2. version of .Net, type of project (is it blazor app or else)
3. what type of Authorization you are using (jwt tokens, AD, cookie etc.).
4. how did you implement/register Authorization services.

Code snippets/repo share will be useful also.

**Comment by iamtheluckyest** [comment]
> 1. version of nuget package you are using.

8.1.0

> 2. version of .Net, type of project (is it blazor app or else)

.Net 5.0, Web API. It's not a Blazor App, but I'm not sure if there is other information here you are asking for.

> 3. what type of Authorization you are using (jwt tokens, AD, cookie etc.).

JWT tokens, eventually with Http Cookie for getting a refresh token, but that part is not implemented yet.

> 4. how did you implement/register Authorization services.

In Startup.ConfigureServices 
```
connectionString = config.GetSection(nameof(MyDatabaseSettings)).GetValue<string>("ConnectionString");
connectionString += "/" + config.GetSection(nameof(MyDatabaseSettings)).GetValue<string>("DatabaseName");

services.AddIdentityMongoDbProvider<AppUser, MongoRole>(identity =>
    {
        identity.Password.RequiredLength = 12;
        identity.Password.RequireLowercase = true;
        identity.Password.RequireUppercase = true;
        identity.Password.RequireNonAlphanumeric = true;
        identity.Password.RequireDigit = true;
    },
    mongo =>
    {
        mongo.ConnectionString = connectionString;
    })
    .AddSignInManager();
```

In Startup.Configure
`app.UseAuthentication();`

> Code snippets/repo share will be useful also.

There is no repo I can share. But hopefully that code snippet is helpful. I did pull down this codebase and modify it to see if `services.AddIdentityCore` would work, and it did seem to resolve the issue I was having. However, it was not thoroughly tested and I'm somewhat new to .Net, so I'm not sure if there are any gotchas I would be unaware of. This was the code I modified in MongoIdentityExtensions.cs:

```
- var builder = services.AddIdentity<TUser, TRole>(setupIdentityAction ?? (x => { }));
+ var builder = services.AddIdentityCore<TUser>(setupIdentityAction ?? (x => { }));

- builder.AddRoleStore<RoleStore<TRole, TKey>>()  
+ builder.AddRoles<TRole>()
+          .AddRoleStore<RoleStore<TRole, TKey>>()
            .AddUserStore<UserStore<TUser, TRole, TKey>>()
            .AddUserManager<UserManager<TUser>>()
            .AddRoleManager<RoleManager<TRole>>()
            .AddDefaultTokenProviders();
```

Of course, I'm not suggesting you actually change that code, as you'd lose support for AddIdentity. But that at least shows how small a change would (hopefully) be needed to support AddIdentityCore.

**Comment by vova3211** [comment]
Thanks.
Yes, we definitely can add 1 more extension method to configure `AddIdentityCore<TUser>`. If you'd like, you can create PR with this changes as well.

One thing that we need to be aware of that `AddIdentityCore<TUser>` configures only User services. You did add `AddRoles<TRole>` which is good, but there are also few more services in compare with `AddIdentity<TUser, TRole>`:
```
services.AddHttpContextAccessor();
.....
services.TryAddScoped<ISecurityStampValidator, SecurityStampValidator<TUser>>();
services.TryAddScoped<ITwoFactorSecurityStampValidator, TwoFactorSecurityStampValidator<TUser>>();
```

The question do we want to add it inside new `AddIdentityCoreMongoDbProvider` method or leave it for user? I'd say first option is better.

**Comment by vova3211** [comment]
@iamtheluckyest 
New package release [8.2.0](https://www.nuget.org/packages/AspNetCore.Identity.Mongo/8.2.0) includes that functionality.
Added `AddMongoDbStores` that allows to register only mongodb stores, so you can register any stuff you want.
Ordinary usage:
```
services
	.AddIdentity<MongoUser, MongoRole>()
	.AddMongoDbStores<MongoUser, MongoRole, ObjectId>(mongo =>
	{
		mongo.ConnectionString = ConnectionString;
	})
	.AddSignInManager()
	.AddDefaultTokenProviders();
```
In your case:
```
services
	.AddIdentityCore<MongoUser>()
        .AddRoles<MongoRole>()
	.AddMongoDbStores<MongoUser, MongoRole, ObjectId>(mongo =>
	{
		mongo.ConnectionString = ConnectionString;
	})
	.AddDefaultTokenProviders();
       // and other stuff
```
